"""
Expanded NPC System - 35+ NPCs per location type
Features:
- Port NPCs (35+)
- City NPCs (35+)
- Pirate Haven NPCs (35+)
- Ship NPCs (crew members)
- Unique personalities and backstories
"""

from typing import Dict, List, Any
import random

# ============================================================================
# PORT NPCs (35 UNIQUE CHARACTERS)
# ============================================================================

PORT_NPCS = [
    {
        "id": "barnacle_bill",
        "name": "Barnacle Bill",
        "title": "Legendary Fisherman",
        "role": "mentor",
        "personality": "wise_gruff",
        "description": "An ancient fisherman covered in barnacles. His eyes have seen every fish in every sea.",
        "faction": "fishermen_guild",
        "initial_disposition": 50,
        "sprite": "old_fisherman",
        "voice_style": "gruff_but_kind",
        "schedule": {"morning": "docks", "afternoon": "tavern", "evening": "docks", "night": "home"},
        "skills_taught": ["basic_fishing", "fish_identification", "weather_reading"],
        "quests_offered": ["first_catch", "golden_mackerel_hunt", "leviathan_tale"],
        "shop_inventory": None,
        "romance_available": False,
        "backstory": "Sailed for 70 years. Lost his ship in the Storm of '82 but gained wisdom."
    },
    {
        "id": "harbor_master_jenkins",
        "name": "Harbor Master Jenkins",
        "title": "Port Authority",
        "role": "official",
        "personality": "bureaucratic_fair",
        "description": "A stern man with immaculate uniform and endless paperwork.",
        "faction": "port_authority",
        "initial_disposition": 40,
        "sprite": "official_uniform",
        "voice_style": "formal_clipped",
        "schedule": {"morning": "office", "afternoon": "docks", "evening": "office", "night": "home"},
        "skills_taught": ["navigation_permits", "trade_licenses"],
        "quests_offered": ["smuggler_investigation", "dock_repairs", "missing_shipment"],
        "shop_inventory": ["permits", "licenses", "maps"],
        "romance_available": False,
        "backstory": "Former naval officer who values order above all else."
    },
    {
        "id": "salty_pete",
        "name": "Salty Pete",
        "title": "Retired Pirate",
        "role": "informant",
        "personality": "shifty_helpful",
        "description": "A one-eyed man with questionable hygiene but valuable information.",
        "faction": "neutral",
        "initial_disposition": 45,
        "sprite": "scruffy_pirate",
        "voice_style": "conspiratorial_raspy",
        "schedule": {"morning": "sleeping", "afternoon": "tavern", "evening": "docks", "night": "tavern"},
        "skills_taught": ["lockpicking", "smuggling_routes", "pirate_contacts"],
        "quests_offered": ["hidden_treasure", "old_debts", "pirate_reunion"],
        "shop_inventory": ["maps", "lockpicks", "disguises"],
        "romance_available": False,
        "backstory": "Served under Captain Redbeard before losing his eye and his nerve."
    },
    {
        "id": "fishwife_martha",
        "name": "Fishwife Martha",
        "title": "Fish Vendor",
        "role": "merchant",
        "personality": "loud_motherly",
        "description": "A large woman with an even larger voice. Knows everyone's business.",
        "faction": "merchants",
        "initial_disposition": 60,
        "sprite": "market_woman",
        "voice_style": "booming_warm",
        "schedule": {"morning": "market", "afternoon": "market", "evening": "home", "night": "home"},
        "skills_taught": ["fish_prices", "bargaining", "gossip_network"],
        "quests_offered": ["delivery_run", "competitor_sabotage", "lost_son"],
        "shop_inventory": ["fish", "bait", "fishing_snacks"],
        "romance_available": False,
        "backstory": "Widowed young, raised six children selling fish. Knows everything."
    },
    {
        "id": "young_tommy",
        "name": "Tommy Waves",
        "title": "Aspiring Fisher",
        "role": "apprentice",
        "personality": "eager_innocent",
        "description": "A bright-eyed boy who dreams of the sea. His father disappeared two years ago.",
        "faction": "none",
        "initial_disposition": 80,
        "sprite": "young_boy",
        "voice_style": "enthusiastic_squeaky",
        "schedule": {"morning": "docks", "afternoon": "school", "evening": "docks", "night": "home"},
        "skills_taught": None,
        "quests_offered": ["tommys_first_catch", "find_fathers_boat", "fishing_competition"],
        "shop_inventory": None,
        "romance_available": False,
        "backstory": "Lost his father to the Golden Depths. Refuses to give up hope."
    },
    {
        "id": "dock_worker_bruno",
        "name": "Bruno Strongarm",
        "title": "Dock Worker",
        "role": "laborer",
        "personality": "simple_loyal",
        "description": "A massive man who can lift barrels two at a time. Not bright but dependable.",
        "faction": "workers_union",
        "initial_disposition": 55,
        "sprite": "muscular_worker",
        "voice_style": "slow_deep",
        "schedule": {"morning": "docks", "afternoon": "docks", "evening": "tavern", "night": "home"},
        "skills_taught": ["heavy_lifting", "cargo_handling"],
        "quests_offered": ["loading_competition", "strike_breaker", "missing_crate"],
        "shop_inventory": None,
        "romance_available": False,
        "backstory": "Born on the docks, will die on the docks. Simple life, simple man."
    },
    {
        "id": "net_mender_agatha",
        "name": "Agatha Threadfinger",
        "title": "Net Mender",
        "role": "craftsman",
        "personality": "patient_precise",
        "description": "An elderly woman whose fingers move like magic through torn nets.",
        "faction": "craftsmen",
        "initial_disposition": 65,
        "sprite": "elderly_woman",
        "voice_style": "soft_precise",
        "schedule": {"morning": "workshop", "afternoon": "docks", "evening": "workshop", "night": "home"},
        "skills_taught": ["net_repair", "rope_work", "sail_mending"],
        "quests_offered": ["rare_thread", "net_competition", "apprentice_needed"],
        "shop_inventory": ["nets", "rope", "sails", "repair_kits"],
        "romance_available": False,
        "backstory": "Mended nets for 50 years. Can fix anything with string."
    },
    {
        "id": "tavern_keeper_rosie",
        "name": "Rosie McTavern",
        "title": "Innkeeper",
        "role": "innkeeper",
        "personality": "warm_protective",
        "description": "A jolly woman who runs the Salty Dog Inn. Knows everyone's secrets.",
        "faction": "innkeepers",
        "initial_disposition": 70,
        "sprite": "innkeeper_woman",
        "voice_style": "warm_motherly",
        "schedule": {"morning": "inn", "afternoon": "inn", "evening": "inn", "night": "inn"},
        "skills_taught": ["cooking_basics", "local_gossip", "room_negotiation"],
        "quests_offered": ["rowdy_customers", "missing_ring", "ghost_room"],
        "shop_inventory": ["rooms", "meals", "drinks", "information"],
        "romance_available": False,
        "backstory": "Former fisher who lost her son Tommy. The inn is her new family."
    },
    {
        "id": "customs_officer_chen",
        "name": "Officer Chen",
        "title": "Customs Inspector",
        "role": "official",
        "personality": "suspicious_thorough",
        "description": "A sharp-eyed man who notices everything. Rumored to be uncorruptible.",
        "faction": "port_authority",
        "initial_disposition": 35,
        "sprite": "inspector_uniform",
        "voice_style": "clipped_suspicious",
        "schedule": {"morning": "customs", "afternoon": "docks", "evening": "customs", "night": "patrol"},
        "skills_taught": ["contraband_detection", "legal_loopholes"],
        "quests_offered": ["smuggler_ring", "false_manifest", "bribery_sting"],
        "shop_inventory": None,
        "romance_available": False,
        "backstory": "Lost family to pirates. Now hunts criminals with cold precision."
    },
    {
        "id": "shipwright_igor",
        "name": "Igor Hammerbolt",
        "title": "Master Shipwright",
        "role": "craftsman",
        "personality": "gruff_perfectionist",
        "description": "A burly man who can build or repair any vessel. Demands quality.",
        "faction": "craftsmen",
        "initial_disposition": 45,
        "sprite": "shipwright",
        "voice_style": "gruff_technical",
        "schedule": {"morning": "shipyard", "afternoon": "shipyard", "evening": "tavern", "night": "home"},
        "skills_taught": ["ship_repair", "upgrade_installation", "hull_assessment"],
        "quests_offered": ["rare_wood", "stolen_tools", "legendary_blueprint"],
        "shop_inventory": ["repairs", "upgrades", "custom_builds"],
        "romance_available": False,
        "backstory": "Third generation shipwright. Built the Crimson Terror herself."
    },
    {
        "id": "fortune_teller_coral",
        "name": "Madame Coral",
        "title": "Seer of Depths",
        "role": "mystic",
        "personality": "mysterious_dramatic",
        "description": "An elderly woman who claims to read futures in fish scales.",
        "faction": "mystics",
        "initial_disposition": 55,
        "sprite": "fortune_teller",
        "voice_style": "ethereal_dramatic",
        "schedule": {"morning": "tent", "afternoon": "tent", "evening": "tent", "night": "spirit_walks"},
        "skills_taught": ["fortune_reading", "curse_removal", "spirit_contact"],
        "quests_offered": ["lost_artifact", "haunted_ship", "prophecy_quest"],
        "shop_inventory": ["fortunes", "charms", "curses_removal"],
        "romance_available": False,
        "backstory": "May have mermaid blood. Her predictions are eerily accurate."
    },
    {
        "id": "bait_seller_finn",
        "name": "Finn Wormdigger",
        "title": "Bait Merchant",
        "role": "merchant",
        "personality": "enthusiastic_smelly",
        "description": "A thin man who's always covered in dirt and worm slime. Loves his work.",
        "faction": "merchants",
        "initial_disposition": 65,
        "sprite": "dirty_merchant",
        "voice_style": "excited_rambling",
        "schedule": {"morning": "digging", "afternoon": "market", "evening": "market", "night": "digging"},
        "skills_taught": ["bait_selection", "worm_breeding", "insect_lore"],
        "quests_offered": ["rare_worm", "giant_grub", "bait_competition"],
        "shop_inventory": ["worms", "grubs", "shrimp", "special_bait"],
        "romance_available": False,
        "backstory": "Found a magical worm as a child. Been obsessed ever since."
    },
    {
        "id": "rope_maker_samuel",
        "name": "Samuel Twist",
        "title": "Rope Maker",
        "role": "craftsman",
        "personality": "quiet_skilled",
        "description": "A silent man whose hands never stop moving. Makes the finest rope.",
        "faction": "craftsmen",
        "initial_disposition": 50,
        "sprite": "craftsman_rope",
        "voice_style": "sparse_soft",
        "schedule": {"morning": "workshop", "afternoon": "workshop", "evening": "home", "night": "home"},
        "skills_taught": ["rope_making", "knot_tying", "snare_crafting"],
        "quests_offered": ["rare_fiber", "rope_bridge", "hangmans_rope"],
        "shop_inventory": ["rope", "cord", "fishing_line", "anchor_chain"],
        "romance_available": False,
        "backstory": "Mute since childhood. Communicates through his craft."
    },
    {
        "id": "lighthouse_keeper_eleanor",
        "name": "Eleanor Lightkeeper",
        "title": "Lighthouse Keeper",
        "role": "guardian",
        "personality": "lonely_vigilant",
        "description": "A solitary woman who guards the light. Hasn't left in twenty years.",
        "faction": "port_authority",
        "initial_disposition": 40,
        "sprite": "lighthouse_keeper",
        "voice_style": "distant_wistful",
        "schedule": {"morning": "lighthouse", "afternoon": "lighthouse", "evening": "lighthouse", "night": "lighthouse"},
        "skills_taught": ["navigation_signals", "storm_prediction", "isolation_survival"],
        "quests_offered": ["lens_repair", "ghost_ships", "her_story"],
        "shop_inventory": None,
        "romance_available": True,
        "backstory": "Waiting for a ship that will never return. Keeps the light for them."
    },
    {
        "id": "drunk_captain_horace",
        "name": "Captain Horace",
        "title": "Disgraced Captain",
        "role": "informant",
        "personality": "tragic_knowledgeable",
        "description": "A once-great captain now drowning in rum. Knows every sea route.",
        "faction": "none",
        "initial_disposition": 50,
        "sprite": "drunk_captain",
        "voice_style": "slurred_eloquent",
        "schedule": {"morning": "tavern", "afternoon": "tavern", "evening": "tavern", "night": "streets"},
        "skills_taught": ["advanced_navigation", "storm_sailing", "secret_routes"],
        "quests_offered": ["redemption_voyage", "lost_crew", "final_journey"],
        "shop_inventory": None,
        "romance_available": False,
        "backstory": "Lost his entire crew to the Kraken. Drinks to forget their screams."
    },
    {
        "id": "fish_cleaner_pablo",
        "name": "Pablo Gutknife",
        "title": "Fish Processor",
        "role": "laborer",
        "personality": "cheerful_gory",
        "description": "A blood-spattered man who sings while gutting fish. Disturbingly happy.",
        "faction": "workers_union",
        "initial_disposition": 60,
        "sprite": "fish_processor",
        "voice_style": "cheerful_accented",
        "schedule": {"morning": "processing", "afternoon": "processing", "evening": "market", "night": "tavern"},
        "skills_taught": ["fish_cleaning", "organ_harvesting", "preservation"],
        "quests_offered": ["special_organs", "rare_fish_prep", "competition"],
        "shop_inventory": ["cleaned_fish", "fish_parts", "oil"],
        "romance_available": False,
        "backstory": "Immigrated from distant shores. Finds joy in simple work."
    },
    {
        "id": "sea_widow_margaret",
        "name": "Margaret Seagrief",
        "title": "Sea Widow",
        "role": "quest_giver",
        "personality": "grieving_hopeful",
        "description": "A woman in black who watches the horizon every day without fail.",
        "faction": "none",
        "initial_disposition": 55,
        "sprite": "widow_black",
        "voice_style": "soft_hopeful",
        "schedule": {"morning": "cliff", "afternoon": "home", "evening": "cliff", "night": "home"},
        "skills_taught": None,
        "quests_offered": ["find_husband", "message_bottle", "memorial_fish"],
        "shop_inventory": None,
        "romance_available": True,
        "backstory": "Husband vanished 5 years ago. Believes he's still alive."
    },
    {
        "id": "retired_admiral",
        "name": "Admiral Thornwood",
        "title": "Retired Admiral",
        "role": "authority",
        "personality": "stern_honorable",
        "description": "Former naval commander now living quietly. Commands respect.",
        "faction": "naval_veterans",
        "initial_disposition": 35,
        "sprite": "admiral_retired",
        "voice_style": "commanding_formal",
        "schedule": {"morning": "walk", "afternoon": "club", "evening": "home", "night": "home"},
        "skills_taught": ["naval_tactics", "fleet_command", "military_contacts"],
        "quests_offered": ["pirate_bounty", "fleet_reunion", "final_mission"],
        "shop_inventory": None,
        "romance_available": False,
        "backstory": "Sank 47 pirate ships. Retired to find peace, found boredom."
    },
    {
        "id": "street_urchin_pip",
        "name": "Pip",
        "title": "Street Urchin",
        "role": "informant",
        "personality": "cunning_survivor",
        "description": "A dirty child with quick fingers and quicker wit. Knows every hiding spot.",
        "faction": "street_rats",
        "initial_disposition": 45,
        "sprite": "street_child",
        "voice_style": "quick_streetwise",
        "schedule": {"morning": "streets", "afternoon": "market", "evening": "docks", "night": "hiding"},
        "skills_taught": ["pickpocketing", "eavesdropping", "hiding"],
        "quests_offered": ["stolen_item", "spy_mission", "gang_trouble"],
        "shop_inventory": ["stolen_goods", "information"],
        "romance_available": False,
        "backstory": "Orphaned by pirates. Survives by wit and speed."
    },
    {
        "id": "ship_doctor_heinrich",
        "name": "Dr. Heinrich",
        "title": "Ship's Doctor",
        "role": "healer",
        "personality": "pragmatic_cynical",
        "description": "A tired man who's seen too many wounds. Drinks too much, heals perfectly.",
        "faction": "medical",
        "initial_disposition": 45,
        "sprite": "doctor_disheveled",
        "voice_style": "tired_precise",
        "schedule": {"morning": "clinic", "afternoon": "tavern", "evening": "clinic", "night": "drinking"},
        "skills_taught": ["first_aid", "surgery", "disease_treatment"],
        "quests_offered": ["plague_ship", "rare_medicine", "mysterious_illness"],
        "shop_inventory": ["medicine", "bandages", "healing_potions"],
        "romance_available": False,
        "backstory": "Lost his license on land. Found purpose healing sailors."
    },
    {
        "id": "cartographer_ming",
        "name": "Ming the Mapmaker",
        "title": "Cartographer",
        "role": "craftsman",
        "personality": "meticulous_curious",
        "description": "An elderly scholar who maps the seas. Every chart is a work of art.",
        "faction": "scholars",
        "initial_disposition": 55,
        "sprite": "cartographer",
        "voice_style": "scholarly_excited",
        "schedule": {"morning": "study", "afternoon": "docks", "evening": "study", "night": "stargazing"},
        "skills_taught": ["map_reading", "chart_making", "star_navigation"],
        "quests_offered": ["uncharted_waters", "ancient_map", "lost_island"],
        "shop_inventory": ["maps", "charts", "compasses", "sextants"],
        "romance_available": False,
        "backstory": "Mapping the world before he dies. Still finding new places."
    },
    {
        "id": "tattoo_artist_jade",
        "name": "Jade Inkfinger",
        "title": "Tattoo Artist",
        "role": "craftsman",
        "personality": "artistic_intimidating",
        "description": "A heavily tattooed woman whose work tells stories. Each piece is magical.",
        "faction": "artists",
        "initial_disposition": 50,
        "sprite": "tattoo_artist",
        "voice_style": "low_artistic",
        "schedule": {"morning": "studio", "afternoon": "studio", "evening": "tavern", "night": "studio"},
        "skills_taught": ["tattoo_magic", "skin_art", "pain_tolerance"],
        "quests_offered": ["rare_ink", "tattoo_removal", "cursed_mark"],
        "shop_inventory": ["tattoos", "magical_marks", "removal"],
        "romance_available": True,
        "backstory": "Each tattoo holds power. She learned from sea witches."
    },
    {
        "id": "old_salts_leader",
        "name": "Old Salt Silas",
        "title": "Retired Sailor",
        "role": "storyteller",
        "personality": "nostalgic_exaggerating",
        "description": "Leader of the old sailors. His stories grow each telling.",
        "faction": "old_salts",
        "initial_disposition": 65,
        "sprite": "old_sailor",
        "voice_style": "rambling_dramatic",
        "schedule": {"morning": "bench", "afternoon": "tavern", "evening": "docks", "night": "tavern"},
        "skills_taught": ["sea_shanties", "tall_tales", "sailor_traditions"],
        "quests_offered": ["prove_story", "find_witness", "final_voyage"],
        "shop_inventory": None,
        "romance_available": False,
        "backstory": "Sailed with every legend. May have been one himself."
    },
    {
        "id": "barrel_maker_olaf",
        "name": "Olaf Stavehand",
        "title": "Cooper",
        "role": "craftsman",
        "personality": "methodical_proud",
        "description": "A large man who makes barrels with precision. Very particular.",
        "faction": "craftsmen",
        "initial_disposition": 50,
        "sprite": "cooper",
        "voice_style": "deliberate_proud",
        "schedule": {"morning": "workshop", "afternoon": "workshop", "evening": "home", "night": "home"},
        "skills_taught": ["barrel_making", "waterproofing", "storage"],
        "quests_offered": ["perfect_barrel", "rare_oak", "leaking_cargo"],
        "shop_inventory": ["barrels", "crates", "storage_solutions"],
        "romance_available": False,
        "backstory": "A barrel he made was found floating 50 years later, still sealed."
    },
    {
        "id": "messenger_swift",
        "name": "Swift",
        "title": "Port Messenger",
        "role": "informant",
        "personality": "fast_terse",
        "description": "A thin runner who delivers messages. Never stops moving.",
        "faction": "messengers",
        "initial_disposition": 55,
        "sprite": "runner",
        "voice_style": "breathless_quick",
        "schedule": {"morning": "running", "afternoon": "running", "evening": "running", "night": "sleeping"},
        "skills_taught": ["speed_running", "message_memory", "shortcut_knowledge"],
        "quests_offered": ["urgent_delivery", "spy_message", "race"],
        "shop_inventory": ["delivery_services"],
        "romance_available": False,
        "backstory": "Born running. Can't sit still. Knows every path."
    },
    {
        "id": "crab_catcher_clyde",
        "name": "Clyde Clawhand",
        "title": "Crab Catcher",
        "role": "specialist",
        "personality": "eccentric_dedicated",
        "description": "A man missing three fingers who only catches crabs. Obsessed.",
        "faction": "fishermen_guild",
        "initial_disposition": 60,
        "sprite": "crab_catcher",
        "voice_style": "excited_focused",
        "schedule": {"morning": "traps", "afternoon": "traps", "evening": "market", "night": "traps"},
        "skills_taught": ["crab_catching", "trap_making", "claw_dodging"],
        "quests_offered": ["giant_crab", "rare_species", "trap_saboteur"],
        "shop_inventory": ["crabs", "crab_traps", "crab_bait"],
        "romance_available": False,
        "backstory": "Crabs took his fingers. He took their freedom. Fair trade."
    },
    {
        "id": "weather_witch_tempest",
        "name": "Tempest",
        "title": "Weather Witch",
        "role": "mystic",
        "personality": "wild_powerful",
        "description": "A wild-haired woman who can smell storms coming. Some say she summons them.",
        "faction": "mystics",
        "initial_disposition": 40,
        "sprite": "weather_witch",
        "voice_style": "intense_prophetic",
        "schedule": {"morning": "cliffs", "afternoon": "tower", "evening": "cliffs", "night": "ritual"},
        "skills_taught": ["weather_prediction", "storm_calling", "wind_reading"],
        "quests_offered": ["storm_quest", "calm_seas", "weather_artifact"],
        "shop_inventory": ["weather_charms", "storm_bottles"],
        "romance_available": True,
        "backstory": "Born during a hurricane. The storms are her siblings."
    },
    {
        "id": "debt_collector_vince",
        "name": "Vince Kneecapper",
        "title": "Debt Collector",
        "role": "antagonist",
        "personality": "threatening_businesslike",
        "description": "A well-dressed man with a brass knuckle handshake. Collects debts.",
        "faction": "criminal",
        "initial_disposition": 30,
        "sprite": "debt_collector",
        "voice_style": "smooth_menacing",
        "schedule": {"morning": "office", "afternoon": "collecting", "evening": "tavern", "night": "collecting"},
        "skills_taught": ["intimidation", "debt_tracking", "negotiation"],
        "quests_offered": ["collect_debt", "protection", "eliminate_competition"],
        "shop_inventory": ["loans", "protection"],
        "romance_available": False,
        "backstory": "Started as a fisherman. Found violence more profitable."
    },
    {
        "id": "pearl_diver_luna",
        "name": "Luna Deepbreath",
        "title": "Pearl Diver",
        "role": "specialist",
        "personality": "graceful_mysterious",
        "description": "A woman who can hold her breath impossibly long. Finds pearls others can't.",
        "faction": "divers",
        "initial_disposition": 50,
        "sprite": "pearl_diver",
        "voice_style": "soft_otherworldly",
        "schedule": {"morning": "diving", "afternoon": "diving", "evening": "beach", "night": "moonbathing"},
        "skills_taught": ["breath_holding", "deep_diving", "pearl_finding"],
        "quests_offered": ["black_pearl", "sunken_treasure", "mermaid_contact"],
        "shop_inventory": ["pearls", "shells", "underwater_finds"],
        "romance_available": True,
        "backstory": "Some say she's half mermaid. She doesn't deny it."
    },
    {
        "id": "sailmaker_patricia",
        "name": "Patricia Windweaver",
        "title": "Sailmaker",
        "role": "craftsman",
        "personality": "practical_innovative",
        "description": "A woman whose sails catch wind like no others. Always experimenting.",
        "faction": "craftsmen",
        "initial_disposition": 55,
        "sprite": "sailmaker",
        "voice_style": "thoughtful_technical",
        "schedule": {"morning": "workshop", "afternoon": "testing", "evening": "workshop", "night": "home"},
        "skills_taught": ["sail_making", "wind_optimization", "repair"],
        "quests_offered": ["new_material", "speed_record", "storm_sail"],
        "shop_inventory": ["sails", "repairs", "custom_designs"],
        "romance_available": False,
        "backstory": "Her grandfather invented the storm sail. She's improving it."
    },
    {
        "id": "guild_recruiter_marcus",
        "name": "Marcus Goldtongue",
        "title": "Guild Recruiter",
        "role": "official",
        "personality": "charismatic_scheming",
        "description": "A charming man who convinces fishers to join the Guild. Always smiling.",
        "faction": "fishermen_guild",
        "initial_disposition": 60,
        "sprite": "recruiter",
        "voice_style": "smooth_persuasive",
        "schedule": {"morning": "guild_hall", "afternoon": "docks", "evening": "tavern", "night": "meetings"},
        "skills_taught": ["persuasion", "guild_benefits", "politics"],
        "quests_offered": ["recruitment_drive", "rival_guild", "political_favor"],
        "shop_inventory": None,
        "romance_available": False,
        "backstory": "Could sell ice to polar bears. Using that gift for the Guild."
    },
    {
        "id": "shell_collector_edgar",
        "name": "Edgar Shellsworth",
        "title": "Conchologist",
        "role": "scholar",
        "personality": "obsessive_gentle",
        "description": "An elderly man who knows every shell in existence. Very particular.",
        "faction": "scholars",
        "initial_disposition": 55,
        "sprite": "collector",
        "voice_style": "precise_passionate",
        "schedule": {"morning": "beach", "afternoon": "study", "evening": "cataloging", "night": "home"},
        "skills_taught": ["shell_identification", "rare_species", "collection_value"],
        "quests_offered": ["rare_shell", "complete_collection", "shell_thief"],
        "shop_inventory": ["shells", "shell_guides", "display_cases"],
        "romance_available": False,
        "backstory": "Has 10,000 shells. Needs 10,001. The hunt never ends."
    },
    {
        "id": "dock_rat_queen",
        "name": "Rat Queen Vera",
        "title": "Pest Controller",
        "role": "specialist",
        "personality": "creepy_useful",
        "description": "A hunched woman surrounded by trained rats. They do her bidding.",
        "faction": "outcasts",
        "initial_disposition": 35,
        "sprite": "rat_queen",
        "voice_style": "whispery_unsettling",
        "schedule": {"morning": "sewers", "afternoon": "docks", "evening": "shadows", "night": "sewers"},
        "skills_taught": ["rat_training", "pest_control", "sewer_knowledge"],
        "quests_offered": ["infestation", "spy_rats", "underground_path"],
        "shop_inventory": ["trained_rats", "pest_services"],
        "romance_available": False,
        "backstory": "The rats saved her as a child. Now she speaks their language."
    },
    {
        "id": "singing_sailor_melodia",
        "name": "Melodia",
        "title": "Shanty Singer",
        "role": "entertainer",
        "personality": "joyful_inspiring",
        "description": "A woman whose singing can make crews work twice as hard. Legendary voice.",
        "faction": "entertainers",
        "initial_disposition": 70,
        "sprite": "singer",
        "voice_style": "melodious_warm",
        "schedule": {"morning": "practicing", "afternoon": "performing", "evening": "tavern", "night": "ships"},
        "skills_taught": ["sea_shanties", "morale_boosting", "crew_coordination"],
        "quests_offered": ["lost_song", "singing_competition", "mermaid_duet"],
        "shop_inventory": ["song_sheets", "instruments"],
        "romance_available": True,
        "backstory": "Taught by mermaids, or so she claims. Her voice is proof."
    }
]

# ============================================================================
# CITY NPCs (35 UNIQUE CHARACTERS)
# ============================================================================

CITY_NPCS = [
    {
        "id": "merchant_marina",
        "name": "Marina Goldscale",
        "title": "Master Merchant",
        "role": "merchant",
        "personality": "calculating_fair",
        "description": "The most successful merchant in the city. Fair but shrewd.",
        "faction": "merchants",
        "initial_disposition": 40,
        "sprite": "merchant_woman",
        "voice_style": "professional_charming",
        "quests_offered": ["rare_fish_delivery", "competitor_info", "lost_husband"],
        "shop_inventory": ["premium_goods", "luxury_items", "trade_contracts"]
    },
    {
        "id": "mayor_cornelius",
        "name": "Mayor Cornelius Whitmore",
        "title": "City Mayor",
        "role": "authority",
        "personality": "pompous_corrupt",
        "description": "A fat man in expensive clothes. More interested in bribes than people.",
        "faction": "city_government",
        "initial_disposition": 45,
        "sprite": "mayor",
        "voice_style": "pompous_oily",
        "quests_offered": ["election_help", "scandal_cover", "rival_elimination"]
    },
    {
        "id": "guild_master_thornwood",
        "name": "Grand Master Thornwood",
        "title": "Fishermen's Guild Master",
        "role": "authority",
        "personality": "traditionalist_stern",
        "description": "Leader of the Fishermen's Guild. Values tradition above all.",
        "faction": "fishermen_guild",
        "initial_disposition": 35,
        "sprite": "guild_master",
        "voice_style": "commanding_formal",
        "quests_offered": ["guild_trial", "tradition_keeper", "innovation_debate"]
    },
    {
        "id": "bank_director_sterling",
        "name": "Director Sterling",
        "title": "Bank Director",
        "role": "financier",
        "personality": "cold_precise",
        "description": "A thin man who sees only numbers. Controls most of the city's wealth.",
        "faction": "bankers",
        "initial_disposition": 30,
        "sprite": "banker",
        "voice_style": "cold_calculated",
        "quests_offered": ["debt_collection", "investment_opportunity", "vault_mystery"]
    },
    {
        "id": "noble_lady_ashworth",
        "name": "Lady Ashworth",
        "title": "Noblewoman",
        "role": "patron",
        "personality": "bored_generous",
        "description": "A wealthy widow seeking excitement. Funds expeditions for entertainment.",
        "faction": "nobility",
        "initial_disposition": 55,
        "sprite": "noble_woman",
        "voice_style": "refined_excited",
        "quests_offered": ["exotic_fish", "dangerous_expedition", "scandal_retrieval"]
    },
    {
        "id": "university_dean",
        "name": "Dean Archimedes",
        "title": "Marine Biology Dean",
        "role": "scholar",
        "personality": "curious_absent_minded",
        "description": "A brilliant but scattered scholar. Knows everything about fish biology.",
        "faction": "scholars",
        "initial_disposition": 60,
        "sprite": "professor",
        "voice_style": "scattered_enthusiastic",
        "quests_offered": ["specimen_collection", "thesis_help", "discovery_expedition"]
    },
    {
        "id": "newspaper_editor",
        "name": "Editor Gazette",
        "title": "Newspaper Editor",
        "role": "informant",
        "personality": "nosy_principled",
        "description": "Runs the city's newspaper. Always looking for a story.",
        "faction": "press",
        "initial_disposition": 50,
        "sprite": "editor",
        "voice_style": "rapid_probing",
        "quests_offered": ["story_investigation", "expose_corruption", "interview_legend"]
    },
    {
        "id": "auction_house_owner",
        "name": "Auctioneer Blackwood",
        "title": "Auction House Owner",
        "role": "merchant",
        "personality": "theatrical_greedy",
        "description": "Sells the rarest catches to the highest bidder. Very dramatic.",
        "faction": "merchants",
        "initial_disposition": 45,
        "sprite": "auctioneer",
        "voice_style": "booming_theatrical",
        "quests_offered": ["rare_acquisition", "auction_rigging", "missing_item"]
    },
    {
        "id": "museum_curator",
        "name": "Curator Penelope",
        "title": "Museum Curator",
        "role": "scholar",
        "personality": "passionate_protective",
        "description": "Guards the Maritime Museum's collection with her life.",
        "faction": "scholars",
        "initial_disposition": 55,
        "sprite": "curator",
        "voice_style": "reverent_informative",
        "quests_offered": ["artifact_donation", "exhibit_setup", "theft_investigation"]
    },
    {
        "id": "chef_master_gustave",
        "name": "Master Chef Gustave",
        "title": "Royal Chef",
        "role": "craftsman",
        "personality": "temperamental_genius",
        "description": "The city's finest chef. Creates masterpieces from fish.",
        "faction": "culinary",
        "initial_disposition": 35,
        "sprite": "chef",
        "voice_style": "dramatic_accented",
        "quests_offered": ["rare_ingredient", "cooking_competition", "secret_recipe"]
    },
    {
        "id": "underground_boss",
        "name": "The Kraken",
        "title": "Crime Lord",
        "role": "antagonist",
        "personality": "ruthless_honorable",
        "description": "Rules the city's underworld. Surprisingly has a code of honor.",
        "faction": "criminal",
        "initial_disposition": 25,
        "sprite": "crime_boss",
        "voice_style": "quiet_menacing",
        "quests_offered": ["smuggling_run", "rival_elimination", "protection_fee"]
    },
    {
        "id": "priest_father_marina",
        "name": "Father Marina",
        "title": "Sea Priest",
        "role": "spiritual",
        "personality": "serene_helpful",
        "description": "Leads the Church of the Sea. Blesses ships and crews.",
        "faction": "church",
        "initial_disposition": 65,
        "sprite": "priest",
        "voice_style": "calming_wise",
        "quests_offered": ["blessing_quest", "lost_soul", "cursed_ship"]
    },
    {
        "id": "spy_master_shadow",
        "name": "Shadow",
        "title": "Intelligence Agent",
        "role": "informant",
        "personality": "paranoid_capable",
        "description": "No one knows who they work for. Knows everything about everyone.",
        "faction": "unknown",
        "initial_disposition": 40,
        "sprite": "spy",
        "voice_style": "whispered_cryptic",
        "quests_offered": ["information_gathering", "courier_mission", "assassination_prevention"]
    },
    {
        "id": "arena_master",
        "name": "Arena Master Brutus",
        "title": "Fish Fighting Arena Owner",
        "role": "entertainer",
        "personality": "loud_competitive",
        "description": "Runs the controversial fish fighting arena. Claims it's a sport.",
        "faction": "entertainers",
        "initial_disposition": 50,
        "sprite": "arena_master",
        "voice_style": "booming_excited",
        "quests_offered": ["champion_fish", "rigged_match", "arena_investigation"]
    },
    {
        "id": "insurance_agent",
        "name": "Agent Prudence",
        "title": "Maritime Insurance Agent",
        "role": "official",
        "personality": "suspicious_thorough",
        "description": "Investigates every claim. Suspects everyone of fraud.",
        "faction": "insurance",
        "initial_disposition": 35,
        "sprite": "insurance_agent",
        "voice_style": "skeptical_detailed",
        "quests_offered": ["fraud_investigation", "ship_assessment", "witness_finding"]
    },
    {
        "id": "fashion_designer_silk",
        "name": "Madame Silk",
        "title": "Fashion Designer",
        "role": "craftsman",
        "personality": "artistic_dramatic",
        "description": "Creates sailor fashion that sweeps the city. Very avant-garde.",
        "faction": "artists",
        "initial_disposition": 50,
        "sprite": "designer",
        "voice_style": "dramatic_accented",
        "quests_offered": ["rare_material", "fashion_show", "scandal_dress"]
    },
    {
        "id": "tavern_owner_brawny",
        "name": "Brawny Beth",
        "title": "Tavern Owner",
        "role": "innkeeper",
        "personality": "tough_fair",
        "description": "Runs the best tavern in the city. Can throw out any troublemaker.",
        "faction": "innkeepers",
        "initial_disposition": 55,
        "sprite": "tavern_owner",
        "voice_style": "gruff_welcoming",
        "quests_offered": ["bar_brawl", "missing_regular", "secret_meeting"]
    },
    {
        "id": "clockmaker_precise",
        "name": "Clockmaker Tick",
        "title": "Master Horologist",
        "role": "craftsman",
        "personality": "obsessive_precise",
        "description": "Makes the most accurate marine chronometers. Counts everything.",
        "faction": "craftsmen",
        "initial_disposition": 45,
        "sprite": "clockmaker",
        "voice_style": "precise_rhythmic",
        "quests_offered": ["rare_component", "stolen_clock", "time_capsule"]
    },
    {
        "id": "fortunate_gambler",
        "name": "Lucky Lou",
        "title": "Professional Gambler",
        "role": "entertainer",
        "personality": "charming_risky",
        "description": "Never seems to lose. There are rumors about how he wins.",
        "faction": "gamblers",
        "initial_disposition": 55,
        "sprite": "gambler",
        "voice_style": "smooth_confident",
        "quests_offered": ["high_stakes", "cheater_expose", "lucky_charm"]
    },
    {
        "id": "exotic_importer",
        "name": "Importer Xander",
        "title": "Exotic Goods Dealer",
        "role": "merchant",
        "personality": "worldly_secretive",
        "description": "Brings rare items from distant lands. Very well-traveled.",
        "faction": "merchants",
        "initial_disposition": 45,
        "sprite": "importer",
        "voice_style": "cultured_mysterious",
        "quests_offered": ["rare_import", "smuggling_favor", "exotic_expedition"]
    },
    {
        "id": "orphanage_matron",
        "name": "Matron Grace",
        "title": "Orphanage Director",
        "role": "caretaker",
        "personality": "kind_desperate",
        "description": "Cares for children of lost sailors. Always needs help.",
        "faction": "charitable",
        "initial_disposition": 70,
        "sprite": "matron",
        "voice_style": "gentle_worried",
        "quests_offered": ["donation_drive", "missing_child", "adoption_help"]
    },
    {
        "id": "retired_pirate_king",
        "name": "Former King Bartholomew",
        "title": "Retired Pirate King",
        "role": "legend",
        "personality": "nostalgic_dangerous",
        "description": "Once ruled the pirates. Now lives quietly, but still commands respect.",
        "faction": "pirates",
        "initial_disposition": 40,
        "sprite": "pirate_king",
        "voice_style": "weary_commanding",
        "quests_offered": ["pirate_past", "hidden_treasure", "old_enemy"]
    },
    {
        "id": "tax_collector",
        "name": "Collector Graves",
        "title": "Royal Tax Collector",
        "role": "official",
        "personality": "efficient_hated",
        "description": "Collects taxes with merciless efficiency. Everyone owes him.",
        "faction": "government",
        "initial_disposition": 30,
        "sprite": "tax_collector",
        "voice_style": "flat_threatening",
        "quests_offered": ["tax_evasion", "debt_forgiveness", "collector_bribe"]
    },
    {
        "id": "alchemist_bubbles",
        "name": "Alchemist Bubbles",
        "title": "Fish Alchemist",
        "role": "craftsman",
        "personality": "eccentric_brilliant",
        "description": "Makes potions from fish parts. Half genius, half mad.",
        "faction": "alchemists",
        "initial_disposition": 55,
        "sprite": "alchemist",
        "voice_style": "excited_scattered",
        "quests_offered": ["rare_ingredient", "potion_testing", "explosion_cleanup"]
    },
    {
        "id": "harbor_patrol_captain",
        "name": "Captain Ironside",
        "title": "Harbor Patrol Captain",
        "role": "authority",
        "personality": "dutiful_incorruptible",
        "description": "Commands the harbor patrol. The only honest official in the city.",
        "faction": "law_enforcement",
        "initial_disposition": 50,
        "sprite": "patrol_captain",
        "voice_style": "stern_fair",
        "quests_offered": ["patrol_assistance", "criminal_capture", "corruption_expose"]
    },
    {
        "id": "traveling_merchant",
        "name": "Wandering Wallace",
        "title": "Traveling Merchant",
        "role": "merchant",
        "personality": "adventurous_unreliable",
        "description": "Appears randomly with strange goods. Never stays long.",
        "faction": "wanderers",
        "initial_disposition": 55,
        "sprite": "wanderer",
        "voice_style": "enthusiastic_cryptic",
        "quests_offered": ["rare_find", "delivery_mission", "mysterious_package"]
    },
    {
        "id": "competing_guild_master",
        "name": "Master Rivaldi",
        "title": "Rival Guild Master",
        "role": "antagonist",
        "personality": "ambitious_cunning",
        "description": "Leads a rival fishing guild. Always plotting against the main guild.",
        "faction": "rival_guild",
        "initial_disposition": 25,
        "sprite": "rival_master",
        "voice_style": "smooth_threatening",
        "quests_offered": ["guild_sabotage", "defection_offer", "competition_rigging"]
    },
    {
        "id": "boat_racer",
        "name": "Speedy Selena",
        "title": "Champion Racer",
        "role": "competitor",
        "personality": "competitive_friendly",
        "description": "The fastest sailor alive. Always looking for a worthy opponent.",
        "faction": "racers",
        "initial_disposition": 60,
        "sprite": "racer",
        "voice_style": "energetic_challenging",
        "quests_offered": ["race_challenge", "speed_record", "sabotage_investigation"]
    },
    {
        "id": "retired_judge",
        "name": "Judge Blackstone",
        "title": "Retired Judge",
        "role": "authority",
        "personality": "wise_disillusioned",
        "description": "Former maritime court judge. Knows all the legal loopholes.",
        "faction": "legal",
        "initial_disposition": 45,
        "sprite": "judge",
        "voice_style": "measured_tired",
        "quests_offered": ["legal_advice", "old_case", "justice_quest"]
    },
    {
        "id": "explorer_society_leader",
        "name": "President Vega",
        "title": "Explorer Society President",
        "role": "patron",
        "personality": "ambitious_visionary",
        "description": "Leads expeditions to uncharted waters. Dreams of discovery.",
        "faction": "explorers",
        "initial_disposition": 55,
        "sprite": "explorer",
        "voice_style": "inspiring_intense",
        "quests_offered": ["expedition_join", "map_completion", "first_contact"]
    },
    {
        "id": "fish_inspector",
        "name": "Inspector Gillman",
        "title": "Fish Quality Inspector",
        "role": "official",
        "personality": "meticulous_bribable",
        "description": "Inspects all fish sold in the city. Has standards... and a price.",
        "faction": "inspectors",
        "initial_disposition": 40,
        "sprite": "inspector",
        "voice_style": "nasal_particular",
        "quests_offered": ["quality_test", "bribery_request", "contamination_investigation"]
    },
    {
        "id": "retired_cook",
        "name": "Old Cookie",
        "title": "Retired Ship's Cook",
        "role": "mentor",
        "personality": "grumpy_wise",
        "description": "Cooked on ships for 50 years. Knows every recipe and every secret.",
        "faction": "culinary",
        "initial_disposition": 50,
        "sprite": "old_cook",
        "voice_style": "grumbling_fond",
        "quests_offered": ["recipe_hunting", "cooking_lesson", "old_memories"]
    },
    {
        "id": "night_watchman",
        "name": "Watchman Owens",
        "title": "Night Watchman",
        "role": "guardian",
        "personality": "vigilant_lonely",
        "description": "Patrols the city at night. Sees things others miss.",
        "faction": "watch",
        "initial_disposition": 50,
        "sprite": "watchman",
        "voice_style": "quiet_observant",
        "quests_offered": ["night_mystery", "patrol_help", "ghost_sighting"]
    },
    {
        "id": "street_performer",
        "name": "Jester Jingles",
        "title": "Street Performer",
        "role": "entertainer",
        "personality": "cheerful_insightful",
        "description": "Entertains crowds but notices everything. Fool or genius?",
        "faction": "entertainers",
        "initial_disposition": 65,
        "sprite": "jester",
        "voice_style": "playful_wise",
        "quests_offered": ["performance_help", "secret_message", "crowd_distraction"]
    }
]

# ============================================================================
# PIRATE HAVEN NPCs (35 UNIQUE CHARACTERS)  
# ============================================================================

PIRATE_HAVEN_NPCS = [
    {
        "id": "captain_redbeard",
        "name": "Captain Redbeard",
        "title": "Pirate Lord",
        "role": "authority",
        "personality": "fierce_honorable",
        "description": "The most feared pirate captain. Has a strict code of honor.",
        "faction": "pirates",
        "initial_disposition": 30,
        "sprite": "pirate_captain",
        "voice_style": "booming_intimidating",
        "quests_offered": ["prove_worth", "raid_mission", "treasure_hunt"]
    },
    {
        "id": "scarlet_sally",
        "name": "Scarlet Sally",
        "title": "Pirate Queen",
        "role": "authority",
        "personality": "cunning_seductive",
        "description": "The deadliest woman on the seas. Beautiful and terrifying.",
        "faction": "pirates",
        "initial_disposition": 35,
        "sprite": "pirate_queen",
        "voice_style": "smooth_dangerous",
        "quests_offered": ["seduction_mission", "revenge_quest", "alliance_negotiation"]
    },
    {
        "id": "black_market_dealer",
        "name": "The Fence",
        "title": "Black Market Dealer",
        "role": "merchant",
        "personality": "shrewd_amoral",
        "description": "Buys and sells anything. No questions asked.",
        "faction": "black_market",
        "initial_disposition": 45,
        "sprite": "shady_dealer",
        "voice_style": "quiet_businesslike",
        "quests_offered": ["stolen_goods", "rare_acquisition", "hot_item"]
    },
    {
        "id": "pirate_doctor",
        "name": "Doc Sawbones",
        "title": "Pirate Surgeon",
        "role": "healer",
        "personality": "drunk_skilled",
        "description": "Always drunk but never misses a cut. Lost count of limbs removed.",
        "faction": "pirates",
        "initial_disposition": 50,
        "sprite": "drunk_doctor",
        "voice_style": "slurred_confident",
        "quests_offered": ["medical_supplies", "plague_cure", "surgery_assist"]
    },
    {
        "id": "tattoo_master",
        "name": "Ink Master Kraken",
        "title": "Pirate Tattoo Artist",
        "role": "craftsman",
        "personality": "artistic_superstitious",
        "description": "His tattoos are said to carry real power. Very selective.",
        "faction": "pirates",
        "initial_disposition": 40,
        "sprite": "tattoo_master",
        "voice_style": "slow_mystical",
        "quests_offered": ["prove_worthy", "rare_ink", "cursed_removal"]
    },
    {
        "id": "weapons_dealer_iron",
        "name": "Iron Meg",
        "title": "Weapons Dealer",
        "role": "merchant",
        "personality": "tough_fair",
        "description": "Sells the best weapons in the haven. Tests each one personally.",
        "faction": "merchants",
        "initial_disposition": 45,
        "sprite": "weapons_dealer",
        "voice_style": "gruff_professional",
        "quests_offered": ["weapon_test", "rare_blade", "arms_smuggling"]
    },
    {
        "id": "pirate_shipwright",
        "name": "Patch the Builder",
        "title": "Pirate Shipwright",
        "role": "craftsman",
        "personality": "creative_reckless",
        "description": "Builds fast ships from whatever's available. Unorthodox but effective.",
        "faction": "craftsmen",
        "initial_disposition": 50,
        "sprite": "pirate_shipwright",
        "voice_style": "manic_enthusiastic",
        "quests_offered": ["salvage_mission", "custom_ship", "sea_trial"]
    },
    {
        "id": "pirate_fortune_teller",
        "name": "Blind Bessie",
        "title": "Seer",
        "role": "mystic",
        "personality": "mysterious_accurate",
        "description": "Blind since birth but sees everything. Pirates fear her predictions.",
        "faction": "mystics",
        "initial_disposition": 50,
        "sprite": "blind_seer",
        "voice_style": "ethereal_certain",
        "quests_offered": ["prophecy_quest", "curse_breaking", "lost_finding"]
    },
    {
        "id": "rum_runner",
        "name": "Rum Runner Rex",
        "title": "Smuggler",
        "role": "merchant",
        "personality": "jovial_slippery",
        "description": "Smuggles the best rum. Always has a deal and an escape route.",
        "faction": "smugglers",
        "initial_disposition": 55,
        "sprite": "smuggler",
        "voice_style": "cheerful_evasive",
        "quests_offered": ["rum_delivery", "navy_evasion", "secret_stash"]
    },
    {
        "id": "pirate_cook",
        "name": "One-Pot Pete",
        "title": "Pirate Cook",
        "role": "craftsman",
        "personality": "creative_resourceful",
        "description": "Can make a meal from anything. His stew is legendary.",
        "faction": "pirates",
        "initial_disposition": 60,
        "sprite": "pirate_cook",
        "voice_style": "friendly_proud",
        "quests_offered": ["ingredient_hunt", "feast_preparation", "recipe_secret"]
    },
    {
        "id": "pirate_historian",
        "name": "Old Chronicles",
        "title": "Pirate Historian",
        "role": "scholar",
        "personality": "obsessive_detailed",
        "description": "Records every pirate deed. His books are worth killing for.",
        "faction": "scholars",
        "initial_disposition": 50,
        "sprite": "pirate_historian",
        "voice_style": "precise_passionate",
        "quests_offered": ["story_verification", "lost_record", "famous_deed"]
    },
    {
        "id": "gambling_den_owner",
        "name": "Snake Eyes Sal",
        "title": "Gambling Den Owner",
        "role": "entertainer",
        "personality": "calculating_friendly",
        "description": "Runs the fairest games in the haven. The house still always wins.",
        "faction": "gamblers",
        "initial_disposition": 50,
        "sprite": "gambling_owner",
        "voice_style": "smooth_calculating",
        "quests_offered": ["debt_collection", "cheater_exposure", "high_stakes"]
    },
    {
        "id": "escaped_slave",
        "name": "Free Marcus",
        "title": "Freed Man",
        "role": "informant",
        "personality": "angry_helpful",
        "description": "Escaped slavery. Now helps others do the same. Hates authority.",
        "faction": "rebels",
        "initial_disposition": 45,
        "sprite": "freed_slave",
        "voice_style": "intense_quiet",
        "quests_offered": ["rescue_mission", "slaver_revenge", "underground_help"]
    },
    {
        "id": "pirate_musician",
        "name": "Squeezebox Stan",
        "title": "Pirate Musician",
        "role": "entertainer",
        "personality": "cheerful_insightful",
        "description": "Plays at every tavern. Knows everyone's secrets through his songs.",
        "faction": "entertainers",
        "initial_disposition": 65,
        "sprite": "musician",
        "voice_style": "musical_knowing",
        "quests_offered": ["song_spy", "morale_mission", "secret_message"]
    },
    {
        "id": "retired_first_mate",
        "name": "First Mate Finn",
        "title": "Retired First Mate",
        "role": "mentor",
        "personality": "experienced_bitter",
        "description": "Served under five captains. Survived them all. That says something.",
        "faction": "pirates",
        "initial_disposition": 45,
        "sprite": "first_mate",
        "voice_style": "cynical_experienced",
        "quests_offered": ["captain_advice", "mutiny_story", "treasure_location"]
    },
    {
        "id": "pirate_blacksmith",
        "name": "Forge",
        "title": "Pirate Blacksmith",
        "role": "craftsman",
        "personality": "silent_skilled",
        "description": "Doesn't speak. His weapons speak for him. Very loudly.",
        "faction": "craftsmen",
        "initial_disposition": 40,
        "sprite": "blacksmith",
        "voice_style": "silent_nods",
        "quests_offered": ["rare_metal", "special_commission", "repair_job"]
    },
    {
        "id": "parrot_trainer",
        "name": "Polly's Mom",
        "title": "Parrot Trainer",
        "role": "specialist",
        "personality": "eccentric_patient",
        "description": "Trains parrots for pirates. Her birds are disturbingly intelligent.",
        "faction": "trainers",
        "initial_disposition": 60,
        "sprite": "parrot_trainer",
        "voice_style": "chirpy_patient",
        "quests_offered": ["parrot_training", "message_delivery", "spy_bird"]
    },
    {
        "id": "pirate_navigator",
        "name": "Stars McGuide",
        "title": "Master Navigator",
        "role": "specialist",
        "personality": "precise_arrogant",
        "description": "Can navigate by stars alone. Insufferably proud of it.",
        "faction": "navigators",
        "initial_disposition": 40,
        "sprite": "navigator",
        "voice_style": "condescending_precise",
        "quests_offered": ["navigation_lesson", "secret_route", "lost_ship"]
    },
    {
        "id": "treasure_hunter",
        "name": "Dig Deep Danny",
        "title": "Treasure Hunter",
        "role": "specialist",
        "personality": "obsessive_paranoid",
        "description": "Has found twelve treasures. Lost them all gambling. Still hunting.",
        "faction": "hunters",
        "initial_disposition": 50,
        "sprite": "treasure_hunter",
        "voice_style": "excited_suspicious",
        "quests_offered": ["treasure_lead", "map_authentication", "dig_partner"]
    },
    {
        "id": "pirate_prostitute",
        "name": "Diamond Doris",
        "title": "Courtesan",
        "role": "informant",
        "personality": "savvy_protective",
        "description": "Knows every captain's secrets. Very protective of her own.",
        "faction": "courtesans",
        "initial_disposition": 45,
        "sprite": "courtesan",
        "voice_style": "sultry_sharp",
        "quests_offered": ["information_extraction", "protection_request", "missing_girl"]
    },
    {
        "id": "powder_monkey_grown",
        "name": "Boom Boom Barry",
        "title": "Explosives Expert",
        "role": "specialist",
        "personality": "manic_dangerous",
        "description": "Started as powder monkey. Now makes the biggest explosions.",
        "faction": "demolitions",
        "initial_disposition": 50,
        "sprite": "explosives_expert",
        "voice_style": "excited_unstable",
        "quests_offered": ["explosion_job", "rare_powder", "sabotage_mission"]
    },
    {
        "id": "quartermaster_strict",
        "name": "Quartermaster Quinn",
        "title": "Haven Quartermaster",
        "role": "official",
        "personality": "fair_strict",
        "description": "Divides all loot fairly. Cross her and lose your share... and fingers.",
        "faction": "pirates",
        "initial_disposition": 40,
        "sprite": "quartermaster",
        "voice_style": "stern_fair",
        "quests_offered": ["loot_dispute", "inventory_audit", "theft_investigation"]
    },
    {
        "id": "ship_wrecking_expert",
        "name": "Wrecker Wally",
        "title": "Ship Salvager",
        "role": "specialist",
        "personality": "opportunistic_skilled",
        "description": "Salvages from wrecks. May have caused some of those wrecks.",
        "faction": "salvagers",
        "initial_disposition": 45,
        "sprite": "salvager",
        "voice_style": "casual_evasive",
        "quests_offered": ["salvage_dive", "wreck_location", "suspicious_sinking"]
    },
    {
        "id": "pirate_lawyer",
        "name": "Legal Louie",
        "title": "Pirate Advocate",
        "role": "specialist",
        "personality": "clever_amoral",
        "description": "Knows maritime law better than judges. Uses it for pirates.",
        "faction": "legal",
        "initial_disposition": 45,
        "sprite": "pirate_lawyer",
        "voice_style": "smooth_technical",
        "quests_offered": ["legal_loophole", "pardon_negotiation", "contract_enforcement"]
    },
    {
        "id": "sea_witch",
        "name": "Sea Witch Morgana",
        "title": "Sea Witch",
        "role": "mystic",
        "personality": "powerful_capricious",
        "description": "A real witch with real powers. Dangerous to deal with.",
        "faction": "witches",
        "initial_disposition": 30,
        "sprite": "sea_witch",
        "voice_style": "echoing_amused",
        "quests_offered": ["magical_favor", "ingredient_gathering", "curse_commission"]
    },
    {
        "id": "former_navy",
        "name": "Turncoat Tom",
        "title": "Former Naval Officer",
        "role": "informant",
        "personality": "conflicted_useful",
        "description": "Deserted the Navy. Has valuable knowledge and endless guilt.",
        "faction": "defectors",
        "initial_disposition": 50,
        "sprite": "former_navy",
        "voice_style": "formal_haunted",
        "quests_offered": ["navy_information", "deserter_rescue", "old_crew"]
    },
    {
        "id": "pirate_bard",
        "name": "Balladeer Bess",
        "title": "Pirate Balladeer",
        "role": "entertainer",
        "personality": "romantic_dramatic",
        "description": "Sings epic ballads of pirate deeds. May exaggerate slightly.",
        "faction": "entertainers",
        "initial_disposition": 60,
        "sprite": "bard",
        "voice_style": "dramatic_melodic",
        "quests_offered": ["inspiring_deed", "true_story", "song_commission"]
    },
    {
        "id": "monkey_handler",
        "name": "Monkey Mike",
        "title": "Monkey Handler",
        "role": "specialist",
        "personality": "strange_useful",
        "description": "Trains monkeys for ship work. Prefers monkey company to humans.",
        "faction": "trainers",
        "initial_disposition": 55,
        "sprite": "monkey_handler",
        "voice_style": "grunty_simple",
        "quests_offered": ["monkey_retrieval", "ship_monkey", "theft_investigation"]
    },
    {
        "id": "cannoneer_master",
        "name": "Big Bertha",
        "title": "Master Cannoneer",
        "role": "specialist",
        "personality": "precise_patient",
        "description": "The best shot in the pirate fleet. Taught by her grandmother.",
        "faction": "gunners",
        "initial_disposition": 45,
        "sprite": "cannoneer",
        "voice_style": "calm_confident",
        "quests_offered": ["target_practice", "cannon_maintenance", "siege_planning"]
    },
    {
        "id": "pirate_recruiter",
        "name": "Press Gang Pete",
        "title": "Crew Recruiter",
        "role": "specialist",
        "personality": "persuasive_ruthless",
        "description": "Recruits new pirates. His methods are... varied.",
        "faction": "pirates",
        "initial_disposition": 40,
        "sprite": "recruiter",
        "voice_style": "friendly_threatening",
        "quests_offered": ["recruitment_help", "rescue_pressed", "escape_plan"]
    },
    {
        "id": "pirate_prince",
        "name": "Prince of Thieves",
        "title": "Pirate Prince",
        "role": "authority",
        "personality": "charming_dangerous",
        "description": "Claims to be actual royalty. May actually be. Definitely dangerous.",
        "faction": "pirates",
        "initial_disposition": 35,
        "sprite": "pirate_prince",
        "voice_style": "refined_menacing",
        "quests_offered": ["royal_mission", "inheritance_claim", "assassination_plot"]
    },
    {
        "id": "map_forger",
        "name": "Fake Map Freddy",
        "title": "Cartographic Artist",
        "role": "craftsman",
        "personality": "artistic_dishonest",
        "description": "Makes convincing fake treasure maps. Sometimes accidentally finds real ones.",
        "faction": "forgers",
        "initial_disposition": 50,
        "sprite": "forger",
        "voice_style": "shifty_defensive",
        "quests_offered": ["fake_map", "real_discovery", "authentication_help"]
    },
    {
        "id": "diver_pirate",
        "name": "Deep Dive Derek",
        "title": "Combat Diver",
        "role": "specialist",
        "personality": "brave_quiet",
        "description": "Boards ships from below. Can hold breath impossibly long.",
        "faction": "divers",
        "initial_disposition": 45,
        "sprite": "diver",
        "voice_style": "brief_intense",
        "quests_offered": ["underwater_mission", "hull_sabotage", "treasure_recovery"]
    },
    {
        "id": "pirate_mother",
        "name": "Mother Mercy",
        "title": "Haven Mother",
        "role": "caretaker",
        "personality": "fierce_protective",
        "description": "Raises pirate orphans. Protected by the entire haven.",
        "faction": "community",
        "initial_disposition": 60,
        "sprite": "pirate_mother",
        "voice_style": "warm_fierce",
        "quests_offered": ["child_rescue", "supplies_needed", "teaching_request"]
    }
]

# Helper function to get all NPCs for a location type
def get_npcs_by_location_type(location_type: str) -> List[Dict]:
    """Get all NPCs for a specific location type"""
    if location_type == "port":
        return PORT_NPCS
    elif location_type == "city":
        return CITY_NPCS
    elif location_type == "pirate_haven":
        return PIRATE_HAVEN_NPCS
    return []

def get_all_npcs() -> List[Dict]:
    """Get all NPCs from all locations"""
    return PORT_NPCS + CITY_NPCS + PIRATE_HAVEN_NPCS

NPC_COUNT = len(PORT_NPCS) + len(CITY_NPCS) + len(PIRATE_HAVEN_NPCS)
