# ========== GO FISH! BIOTOPE FISH DATABASE - FRESHWATER LAKE ==========
# 25 Lake Fish Species
# ~500+ lines of backend code

LAKE_FISH = {
    # POND (Stage 1) - 5 fish
    "bluegill": {
        "id": "bluegill",
        "name": "Bluegill",
        "scientific_name": "Lepomis macrochirus",
        "biotope": "freshwater_lake",
        "stage": "pond",
        "rarity": "common",
        "size_range": {"min": 10, "max": 30, "unit": "cm"},
        "weight_range": {"min": 0.05, "max": 0.5, "unit": "kg"},
        "base_value": 15,
        "xp_reward": 5,
        "description": "A colorful panfish beloved by beginners.",
        "stats": {
            "strength": 1,
            "speed": 3,
            "stamina": 2,
            "fight_rating": "Easy"
        },
        "best_bait": ["worm", "cricket", "bread"],
        "best_time": ["morning", "evening"],
        "season": ["spring", "summer"],
        "cooking_grade": "A",
        "flavor_profile": "Sweet, mild, flaky",
        "icon": "🐟",
        "color": "#4169E1"
    },
    "pumpkinseed": {
        "id": "pumpkinseed",
        "name": "Pumpkinseed Sunfish",
        "scientific_name": "Lepomis gibbosus",
        "biotope": "freshwater_lake",
        "stage": "pond",
        "rarity": "common",
        "size_range": {"min": 8, "max": 25, "unit": "cm"},
        "weight_range": {"min": 0.03, "max": 0.4, "unit": "kg"},
        "base_value": 12,
        "xp_reward": 4,
        "description": "A beautiful sunfish with orange and blue markings.",
        "stats": {
            "strength": 1,
            "speed": 3,
            "stamina": 2,
            "fight_rating": "Easy"
        },
        "best_bait": ["worm", "grub", "small_fly"],
        "best_time": ["midday"],
        "season": ["spring", "summer"],
        "cooking_grade": "A",
        "flavor_profile": "Sweet, delicate",
        "icon": "🐟",
        "color": "#FFA500"
    },
    "common_carp": {
        "id": "common_carp",
        "name": "Common Carp",
        "scientific_name": "Cyprinus carpio",
        "biotope": "freshwater_lake",
        "stage": "pond",
        "rarity": "common",
        "size_range": {"min": 30, "max": 100, "unit": "cm"},
        "weight_range": {"min": 1, "max": 25, "unit": "kg"},
        "base_value": 40,
        "xp_reward": 12,
        "description": "A hardy fish that can grow to impressive sizes.",
        "stats": {
            "strength": 6,
            "speed": 3,
            "stamina": 7,
            "fight_rating": "Medium"
        },
        "best_bait": ["corn", "dough_ball", "boilie"],
        "best_time": ["morning", "evening"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "B",
        "flavor_profile": "Earthy, firm",
        "icon": "🐟",
        "color": "#CD853F"
    },
    "golden_shiner": {
        "id": "golden_shiner",
        "name": "Golden Shiner",
        "scientific_name": "Notemigonus crysoleucas",
        "biotope": "freshwater_lake",
        "stage": "pond",
        "rarity": "common",
        "size_range": {"min": 8, "max": 25, "unit": "cm"},
        "weight_range": {"min": 0.02, "max": 0.3, "unit": "kg"},
        "base_value": 8,
        "xp_reward": 3,
        "description": "A shimmering baitfish with golden scales.",
        "stats": {
            "strength": 1,
            "speed": 5,
            "stamina": 2,
            "fight_rating": "Easy"
        },
        "best_bait": ["bread", "tiny_worm", "dough"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "C",
        "flavor_profile": "Bony, used as bait",
        "icon": "✨",
        "color": "#FFD700"
    },
    "bullhead_catfish": {
        "id": "bullhead_catfish",
        "name": "Brown Bullhead",
        "scientific_name": "Ameiurus nebulosus",
        "biotope": "freshwater_lake",
        "stage": "pond",
        "rarity": "common",
        "size_range": {"min": 15, "max": 45, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 2, "unit": "kg"},
        "base_value": 25,
        "xp_reward": 8,
        "description": "A small catfish that feeds at night.",
        "stats": {
            "strength": 2,
            "speed": 2,
            "stamina": 4,
            "fight_rating": "Easy"
        },
        "best_bait": ["worm", "chicken_liver", "stinkbait"],
        "best_time": ["night", "dusk"],
        "season": ["spring", "summer"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, sweet, firm",
        "icon": "🐱",
        "color": "#8B4513"
    },
    
    # SHALLOW LAKE (Stage 2) - 5 fish
    "largemouth_bass": {
        "id": "largemouth_bass",
        "name": "Largemouth Bass",
        "scientific_name": "Micropterus salmoides",
        "biotope": "freshwater_lake",
        "stage": "shallow_lake",
        "rarity": "common",
        "size_range": {"min": 25, "max": 65, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 10, "unit": "kg"},
        "base_value": 80,
        "xp_reward": 25,
        "description": "The king of freshwater sport fishing.",
        "stats": {
            "strength": 6,
            "speed": 5,
            "stamina": 5,
            "fight_rating": "Medium-Hard"
        },
        "best_bait": ["plastic_worm", "crankbait", "live_shiner"],
        "best_time": ["dawn", "dusk"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "B+",
        "flavor_profile": "Mild, white, flaky",
        "icon": "🐟",
        "color": "#228B22"
    },
    "northern_pike": {
        "id": "northern_pike",
        "name": "Northern Pike",
        "scientific_name": "Esox lucius",
        "biotope": "freshwater_lake",
        "stage": "shallow_lake",
        "rarity": "uncommon",
        "size_range": {"min": 40, "max": 130, "unit": "cm"},
        "weight_range": {"min": 1, "max": 20, "unit": "kg"},
        "base_value": 150,
        "xp_reward": 45,
        "description": "A fierce predator with razor-sharp teeth.",
        "stats": {
            "strength": 7,
            "speed": 8,
            "stamina": 5,
            "fight_rating": "Hard"
        },
        "best_bait": ["spoon_lure", "live_bait", "jerkbait"],
        "best_time": ["morning", "overcast"],
        "season": ["spring", "fall"],
        "cooking_grade": "B",
        "flavor_profile": "White, firm, bony",
        "icon": "🐊",
        "color": "#2F4F4F"
    },
    "walleye": {
        "id": "walleye",
        "name": "Walleye",
        "scientific_name": "Sander vitreus",
        "biotope": "freshwater_lake",
        "stage": "shallow_lake",
        "rarity": "uncommon",
        "size_range": {"min": 30, "max": 80, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 9, "unit": "kg"},
        "base_value": 120,
        "xp_reward": 40,
        "description": "A prized game fish with excellent night vision.",
        "stats": {
            "strength": 5,
            "speed": 5,
            "stamina": 6,
            "fight_rating": "Medium"
        },
        "best_bait": ["leech", "minnow", "jig"],
        "best_time": ["dusk", "dawn", "night"],
        "season": ["spring", "fall"],
        "cooking_grade": "A++",
        "flavor_profile": "Sweet, mild, firm",
        "icon": "🐟",
        "color": "#DAA520"
    },
    "yellow_perch": {
        "id": "yellow_perch",
        "name": "Yellow Perch",
        "scientific_name": "Perca flavescens",
        "biotope": "freshwater_lake",
        "stage": "shallow_lake",
        "rarity": "common",
        "size_range": {"min": 15, "max": 35, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 1, "unit": "kg"},
        "base_value": 35,
        "xp_reward": 12,
        "description": "A schooling fish with distinctive vertical bars.",
        "stats": {
            "strength": 2,
            "speed": 4,
            "stamina": 3,
            "fight_rating": "Easy"
        },
        "best_bait": ["minnow", "worm", "small_jig"],
        "best_time": ["morning", "afternoon"],
        "season": ["spring", "fall", "winter"],
        "cooking_grade": "A+",
        "flavor_profile": "Sweet, delicate, flaky",
        "icon": "🐟",
        "color": "#FFD700"
    },
    "crappie": {
        "id": "crappie",
        "name": "Black Crappie",
        "scientific_name": "Pomoxis nigromaculatus",
        "biotope": "freshwater_lake",
        "stage": "shallow_lake",
        "rarity": "common",
        "size_range": {"min": 15, "max": 40, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 2, "unit": "kg"},
        "base_value": 45,
        "xp_reward": 15,
        "description": "A popular panfish known for schooling behavior.",
        "stats": {
            "strength": 2,
            "speed": 3,
            "stamina": 3,
            "fight_rating": "Easy"
        },
        "best_bait": ["minnow", "small_jig", "tube_bait"],
        "best_time": ["dawn", "dusk"],
        "season": ["spring", "fall"],
        "cooking_grade": "A+",
        "flavor_profile": "Sweet, mild, tender",
        "icon": "🐟",
        "color": "#696969"
    },
    
    # DEEP LAKE (Stage 3) - 5 fish
    "lake_trout": {
        "id": "lake_trout",
        "name": "Lake Trout",
        "scientific_name": "Salvelinus namaycush",
        "biotope": "freshwater_lake",
        "stage": "deep_lake",
        "rarity": "uncommon",
        "size_range": {"min": 40, "max": 100, "unit": "cm"},
        "weight_range": {"min": 2, "max": 30, "unit": "kg"},
        "base_value": 200,
        "xp_reward": 60,
        "description": "A cold-water predator found in deep, clear lakes.",
        "stats": {
            "strength": 6,
            "speed": 5,
            "stamina": 7,
            "fight_rating": "Medium-Hard"
        },
        "best_bait": ["live_bait", "spoon_lure", "downrigger"],
        "best_time": ["early_morning"],
        "season": ["spring", "fall", "winter"],
        "cooking_grade": "A+",
        "flavor_profile": "Rich, oily, salmon-like",
        "icon": "🐟",
        "color": "#2E8B57"
    },
    "cisco": {
        "id": "cisco",
        "name": "Lake Cisco",
        "scientific_name": "Coregonus artedi",
        "biotope": "freshwater_lake",
        "stage": "deep_lake",
        "rarity": "common",
        "size_range": {"min": 20, "max": 40, "unit": "cm"},
        "weight_range": {"min": 0.2, "max": 1.5, "unit": "kg"},
        "base_value": 50,
        "xp_reward": 18,
        "description": "A silvery fish found in deep, cold lakes.",
        "stats": {
            "strength": 2,
            "speed": 5,
            "stamina": 4,
            "fight_rating": "Easy"
        },
        "best_bait": ["small_minnow", "fly", "tiny_jig"],
        "best_time": ["evening"],
        "season": ["fall", "winter"],
        "cooking_grade": "A",
        "flavor_profile": "Delicate, sweet",
        "icon": "🐟",
        "color": "#C0C0C0"
    },
    "burbot": {
        "id": "burbot",
        "name": "Burbot",
        "scientific_name": "Lota lota",
        "biotope": "freshwater_lake",
        "stage": "deep_lake",
        "rarity": "uncommon",
        "size_range": {"min": 30, "max": 80, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 8, "unit": "kg"},
        "base_value": 90,
        "xp_reward": 30,
        "description": "The only freshwater cod, with a single chin barbel.",
        "stats": {
            "strength": 4,
            "speed": 3,
            "stamina": 6,
            "fight_rating": "Medium"
        },
        "best_bait": ["cut_bait", "minnow", "worm"],
        "best_time": ["night", "winter"],
        "season": ["winter"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, cod-like, firm",
        "icon": "🐍",
        "color": "#8B7355"
    },
    "lake_sturgeon": {
        "id": "lake_sturgeon",
        "name": "Lake Sturgeon",
        "scientific_name": "Acipenser fulvescens",
        "biotope": "freshwater_lake",
        "stage": "deep_lake",
        "rarity": "rare",
        "size_range": {"min": 80, "max": 200, "unit": "cm"},
        "weight_range": {"min": 5, "max": 100, "unit": "kg"},
        "base_value": 400,
        "xp_reward": 100,
        "description": "An ancient fish that can live over 100 years.",
        "stats": {
            "strength": 9,
            "speed": 3,
            "stamina": 9,
            "fight_rating": "Hard"
        },
        "best_bait": ["worm_ball", "crayfish", "cut_bait"],
        "best_time": ["dawn", "dusk"],
        "season": ["spring", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Firm, mild, caviar source",
        "icon": "🦴",
        "color": "#696969"
    },
    "freshwater_drum": {
        "id": "freshwater_drum",
        "name": "Freshwater Drum",
        "scientific_name": "Aplodinotus grunniens",
        "biotope": "freshwater_lake",
        "stage": "deep_lake",
        "rarity": "common",
        "size_range": {"min": 30, "max": 75, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 15, "unit": "kg"},
        "base_value": 55,
        "xp_reward": 20,
        "description": "Named for the drumming sound males make.",
        "stats": {
            "strength": 5,
            "speed": 4,
            "stamina": 5,
            "fight_rating": "Medium"
        },
        "best_bait": ["crayfish", "worm", "minnow"],
        "best_time": ["evening"],
        "season": ["summer"],
        "cooking_grade": "B",
        "flavor_profile": "Firm, mild",
        "icon": "🥁",
        "color": "#778899"
    },
    
    # MOUNTAIN LAKE (Stage 4) - 5 fish
    "golden_trout": {
        "id": "golden_trout",
        "name": "Golden Trout",
        "scientific_name": "Oncorhynchus mykiss aguabonita",
        "biotope": "freshwater_lake",
        "stage": "mountain_lake",
        "rarity": "rare",
        "size_range": {"min": 15, "max": 45, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 3, "unit": "kg"},
        "base_value": 350,
        "xp_reward": 90,
        "description": "A stunningly beautiful high-altitude trout.",
        "stats": {
            "strength": 3,
            "speed": 6,
            "stamina": 5,
            "fight_rating": "Medium"
        },
        "best_bait": ["dry_fly", "nymph", "small_spinner"],
        "best_time": ["morning", "evening"],
        "season": ["summer"],
        "cooking_grade": "A+",
        "flavor_profile": "Delicate, sweet, rare",
        "icon": "✨",
        "color": "#FFD700"
    },
    "brook_char": {
        "id": "brook_char",
        "name": "Brook Trout",
        "scientific_name": "Salvelinus fontinalis",
        "biotope": "freshwater_lake",
        "stage": "mountain_lake",
        "rarity": "uncommon",
        "size_range": {"min": 15, "max": 50, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 4, "unit": "kg"},
        "base_value": 120,
        "xp_reward": 40,
        "description": "A beautiful char with vermiculate markings.",
        "stats": {
            "strength": 3,
            "speed": 5,
            "stamina": 4,
            "fight_rating": "Medium"
        },
        "best_bait": ["fly", "worm", "spinner"],
        "best_time": ["morning", "evening"],
        "season": ["spring", "fall"],
        "cooking_grade": "A+",
        "flavor_profile": "Sweet, delicate, firm",
        "icon": "🐟",
        "color": "#FF6347"
    },
    "arctic_grayling": {
        "id": "arctic_grayling",
        "name": "Arctic Grayling",
        "scientific_name": "Thymallus arcticus",
        "biotope": "freshwater_lake",
        "stage": "mountain_lake",
        "rarity": "uncommon",
        "size_range": {"min": 20, "max": 50, "unit": "cm"},
        "weight_range": {"min": 0.2, "max": 2.5, "unit": "kg"},
        "base_value": 150,
        "xp_reward": 45,
        "description": "Famous for its large, sail-like dorsal fin.",
        "stats": {
            "strength": 3,
            "speed": 6,
            "stamina": 4,
            "fight_rating": "Medium"
        },
        "best_bait": ["dry_fly", "nymph", "small_lure"],
        "best_time": ["afternoon"],
        "season": ["summer"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, delicate, thyme-scented",
        "icon": "⛵",
        "color": "#9370DB"
    },
    "mountain_whitefish": {
        "id": "mountain_whitefish",
        "name": "Mountain Whitefish",
        "scientific_name": "Prosopium williamsoni",
        "biotope": "freshwater_lake",
        "stage": "mountain_lake",
        "rarity": "common",
        "size_range": {"min": 20, "max": 45, "unit": "cm"},
        "weight_range": {"min": 0.2, "max": 2, "unit": "kg"},
        "base_value": 60,
        "xp_reward": 22,
        "description": "A silvery fish found in cold mountain waters.",
        "stats": {
            "strength": 2,
            "speed": 4,
            "stamina": 4,
            "fight_rating": "Easy"
        },
        "best_bait": ["nymph", "small_worm", "maggot"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, white, flaky",
        "icon": "🐟",
        "color": "#E0E0E0"
    },
    "kokanee_salmon": {
        "id": "kokanee_salmon",
        "name": "Kokanee Salmon",
        "scientific_name": "Oncorhynchus nerka",
        "biotope": "freshwater_lake",
        "stage": "mountain_lake",
        "rarity": "uncommon",
        "size_range": {"min": 25, "max": 45, "unit": "cm"},
        "weight_range": {"min": 0.3, "max": 2.5, "unit": "kg"},
        "base_value": 100,
        "xp_reward": 35,
        "description": "A landlocked sockeye salmon.",
        "stats": {
            "strength": 4,
            "speed": 6,
            "stamina": 5,
            "fight_rating": "Medium"
        },
        "best_bait": ["wedding_ring", "dodger", "corn"],
        "best_time": ["dawn", "dusk"],
        "season": ["summer", "fall"],
        "cooking_grade": "A+",
        "flavor_profile": "Rich, red, salmon-like",
        "icon": "🐟",
        "color": "#FF6B6B"
    },
    
    # ANCIENT LAKE (Stage 5) - 5 fish
    "baikal_omul": {
        "id": "baikal_omul",
        "name": "Baikal Omul",
        "scientific_name": "Coregonus migratorius",
        "biotope": "freshwater_lake",
        "stage": "ancient_lake",
        "rarity": "rare",
        "size_range": {"min": 30, "max": 50, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 3, "unit": "kg"},
        "base_value": 300,
        "xp_reward": 80,
        "description": "Endemic to Lake Baikal, the world's deepest lake.",
        "stats": {
            "strength": 3,
            "speed": 5,
            "stamina": 5,
            "fight_rating": "Medium"
        },
        "best_bait": ["amphipod", "small_fish"],
        "best_time": ["dawn", "dusk"],
        "season": ["summer", "fall"],
        "cooking_grade": "A++",
        "flavor_profile": "Delicate, sweet, prized",
        "icon": "🐟",
        "color": "#B0C4DE"
    },
    "golomyanka": {
        "id": "golomyanka",
        "name": "Baikal Oilfish",
        "scientific_name": "Comephorus baikalensis",
        "biotope": "freshwater_lake",
        "stage": "ancient_lake",
        "rarity": "rare",
        "size_range": {"min": 15, "max": 25, "unit": "cm"},
        "weight_range": {"min": 0.02, "max": 0.08, "unit": "kg"},
        "base_value": 250,
        "xp_reward": 70,
        "description": "A transparent fish that dissolves in sunlight.",
        "stats": {
            "strength": 1,
            "speed": 4,
            "stamina": 3,
            "fight_rating": "Easy"
        },
        "best_bait": ["tiny_amphipod", "plankton_lure"],
        "best_time": ["night"],
        "season": ["all"],
        "cooking_grade": "N/A",
        "flavor_profile": "Mostly oil, used medicinally",
        "icon": "👻",
        "color": "#FFFFFF"
    },
    "prehistoric_sturgeon": {
        "id": "prehistoric_sturgeon",
        "name": "Kaluga Sturgeon",
        "scientific_name": "Huso dauricus",
        "biotope": "freshwater_lake",
        "stage": "ancient_lake",
        "rarity": "epic",
        "size_range": {"min": 150, "max": 500, "unit": "cm"},
        "weight_range": {"min": 50, "max": 1000, "unit": "kg"},
        "base_value": 2000,
        "xp_reward": 350,
        "description": "One of the largest freshwater fish in the world.",
        "stats": {
            "strength": 10,
            "speed": 3,
            "stamina": 10,
            "fight_rating": "Legendary"
        },
        "best_bait": ["large_fish", "lamprey"],
        "best_time": ["dawn"],
        "season": ["spring"],
        "cooking_grade": "A++",
        "flavor_profile": "Prized for meat and caviar",
        "icon": "🦴",
        "color": "#696969"
    },
    "giant_catfish": {
        "id": "giant_catfish",
        "name": "Wels Catfish",
        "scientific_name": "Silurus glanis",
        "biotope": "freshwater_lake",
        "stage": "ancient_lake",
        "rarity": "epic",
        "size_range": {"min": 100, "max": 300, "unit": "cm"},
        "weight_range": {"min": 20, "max": 150, "unit": "kg"},
        "base_value": 800,
        "xp_reward": 200,
        "description": "Europe's largest freshwater fish.",
        "stats": {
            "strength": 9,
            "speed": 4,
            "stamina": 8,
            "fight_rating": "Hard"
        },
        "best_bait": ["large_fish", "frog", "large_worm"],
        "best_time": ["night"],
        "season": ["summer"],
        "cooking_grade": "B+",
        "flavor_profile": "Firm, mild, slightly fatty",
        "icon": "🐱",
        "color": "#4A4A4A"
    },
    "ancient_gar": {
        "id": "ancient_gar",
        "name": "Alligator Gar",
        "scientific_name": "Atractosteus spatula",
        "biotope": "freshwater_lake",
        "stage": "ancient_lake",
        "rarity": "rare",
        "size_range": {"min": 100, "max": 250, "unit": "cm"},
        "weight_range": {"min": 10, "max": 130, "unit": "kg"},
        "base_value": 500,
        "xp_reward": 130,
        "description": "A living fossil with armor-like scales.",
        "stats": {
            "strength": 8,
            "speed": 5,
            "stamina": 7,
            "fight_rating": "Hard"
        },
        "best_bait": ["large_fish", "cut_bait"],
        "best_time": ["morning", "evening"],
        "season": ["summer"],
        "cooking_grade": "B",
        "flavor_profile": "Firm, white, requires preparation",
        "icon": "🐊",
        "color": "#556B2F"
    }
}
