# ========== GO FISH! BIOTOPE FISH DATABASE - RIVER ==========
# 25 River Fish Species
# ~500+ lines of backend code

RIVER_FISH = {
    # MOUNTAIN STREAM (Stage 1) - 5 fish
    "rainbow_trout": {
        "id": "rainbow_trout",
        "name": "Rainbow Trout",
        "scientific_name": "Oncorhynchus mykiss",
        "biotope": "river",
        "stage": "mountain_stream",
        "rarity": "common",
        "size_range": {"min": 20, "max": 60, "unit": "cm"},
        "weight_range": {"min": 0.2, "max": 5, "unit": "kg"},
        "base_value": 60,
        "xp_reward": 20,
        "description": "A colorful trout with a distinctive pink stripe.",
        "stats": {
            "strength": 4,
            "speed": 6,
            "stamina": 5,
            "fight_rating": "Medium"
        },
        "best_bait": ["fly", "spinner", "worm"],
        "best_time": ["morning", "evening"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "A+",
        "flavor_profile": "Delicate, nutty, pink flesh",
        "icon": "🌈",
        "color": "#FF69B4"
    },
    "brown_trout": {
        "id": "brown_trout",
        "name": "Brown Trout",
        "scientific_name": "Salmo trutta",
        "biotope": "river",
        "stage": "mountain_stream",
        "rarity": "uncommon",
        "size_range": {"min": 25, "max": 80, "unit": "cm"},
        "weight_range": {"min": 0.3, "max": 10, "unit": "kg"},
        "base_value": 100,
        "xp_reward": 35,
        "description": "A wary, intelligent trout with golden spots.",
        "stats": {
            "strength": 5,
            "speed": 5,
            "stamina": 6,
            "fight_rating": "Medium-Hard"
        },
        "best_bait": ["streamer", "nymph", "minnow"],
        "best_time": ["dawn", "dusk", "night"],
        "season": ["spring", "fall"],
        "cooking_grade": "A+",
        "flavor_profile": "Rich, earthy, firm",
        "icon": "🐟",
        "color": "#8B4513"
    },
    "brook_trout": {
        "id": "brook_trout",
        "name": "Brook Trout",
        "scientific_name": "Salvelinus fontinalis",
        "biotope": "river",
        "stage": "mountain_stream",
        "rarity": "common",
        "size_range": {"min": 15, "max": 40, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 3, "unit": "kg"},
        "base_value": 50,
        "xp_reward": 18,
        "description": "A beautiful native char with vermiculate markings.",
        "stats": {
            "strength": 3,
            "speed": 5,
            "stamina": 4,
            "fight_rating": "Easy-Medium"
        },
        "best_bait": ["dry_fly", "worm", "small_spinner"],
        "best_time": ["morning", "overcast"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "A+",
        "flavor_profile": "Sweet, delicate, orange flesh",
        "icon": "🐟",
        "color": "#FF6347"
    },
    "sculpin": {
        "id": "sculpin",
        "name": "Mottled Sculpin",
        "scientific_name": "Cottus bairdii",
        "biotope": "river",
        "stage": "mountain_stream",
        "rarity": "common",
        "size_range": {"min": 5, "max": 15, "unit": "cm"},
        "weight_range": {"min": 0.01, "max": 0.1, "unit": "kg"},
        "base_value": 15,
        "xp_reward": 5,
        "description": "A small bottom-dwelling fish that hides under rocks.",
        "stats": {
            "strength": 1,
            "speed": 3,
            "stamina": 3,
            "fight_rating": "Easy"
        },
        "best_bait": ["tiny_worm", "larva"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "C",
        "flavor_profile": "Small, used as bait",
        "icon": "🪨",
        "color": "#8B7355"
    },
    "dace": {
        "id": "dace",
        "name": "Longnose Dace",
        "scientific_name": "Rhinichthys cataractae",
        "biotope": "river",
        "stage": "mountain_stream",
        "rarity": "common",
        "size_range": {"min": 5, "max": 15, "unit": "cm"},
        "weight_range": {"min": 0.01, "max": 0.08, "unit": "kg"},
        "base_value": 10,
        "xp_reward": 3,
        "description": "A small minnow found in fast-flowing streams.",
        "stats": {
            "strength": 1,
            "speed": 5,
            "stamina": 3,
            "fight_rating": "Easy"
        },
        "best_bait": ["tiny_fly", "bread_crumb"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "D",
        "flavor_profile": "Too small, used as bait",
        "icon": "🐟",
        "color": "#A0522D"
    },
    
    # FOREST CREEK (Stage 2) - 5 fish
    "smallmouth_bass": {
        "id": "smallmouth_bass",
        "name": "Smallmouth Bass",
        "scientific_name": "Micropterus dolomieu",
        "biotope": "river",
        "stage": "forest_creek",
        "rarity": "common",
        "size_range": {"min": 20, "max": 55, "unit": "cm"},
        "weight_range": {"min": 0.3, "max": 5, "unit": "kg"},
        "base_value": 70,
        "xp_reward": 25,
        "description": "Pound-for-pound, one of the best fighting fish.",
        "stats": {
            "strength": 6,
            "speed": 7,
            "stamina": 6,
            "fight_rating": "Hard"
        },
        "best_bait": ["crayfish", "tube_bait", "jerkbait"],
        "best_time": ["morning", "evening"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "B+",
        "flavor_profile": "Mild, white, flaky",
        "icon": "🐟",
        "color": "#556B2F"
    },
    "rock_bass": {
        "id": "rock_bass",
        "name": "Rock Bass",
        "scientific_name": "Ambloplites rupestris",
        "biotope": "river",
        "stage": "forest_creek",
        "rarity": "common",
        "size_range": {"min": 12, "max": 30, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 1, "unit": "kg"},
        "base_value": 30,
        "xp_reward": 10,
        "description": "A red-eyed panfish found near rocky structures.",
        "stats": {
            "strength": 2,
            "speed": 3,
            "stamina": 3,
            "fight_rating": "Easy"
        },
        "best_bait": ["worm", "small_crayfish", "grub"],
        "best_time": ["any"],
        "season": ["spring", "summer"],
        "cooking_grade": "A",
        "flavor_profile": "Sweet, firm panfish",
        "icon": "🪨",
        "color": "#8B4513"
    },
    "creek_chub": {
        "id": "creek_chub",
        "name": "Creek Chub",
        "scientific_name": "Semotilus atromaculatus",
        "biotope": "river",
        "stage": "forest_creek",
        "rarity": "common",
        "size_range": {"min": 10, "max": 30, "unit": "cm"},
        "weight_range": {"min": 0.05, "max": 0.5, "unit": "kg"},
        "base_value": 20,
        "xp_reward": 7,
        "description": "A common minnow that builds gravel nests.",
        "stats": {
            "strength": 2,
            "speed": 4,
            "stamina": 3,
            "fight_rating": "Easy"
        },
        "best_bait": ["worm", "bread", "small_fly"],
        "best_time": ["any"],
        "season": ["spring", "summer"],
        "cooking_grade": "C",
        "flavor_profile": "Bony, often used as bait",
        "icon": "🐟",
        "color": "#696969"
    },
    "fallfish": {
        "id": "fallfish",
        "name": "Fallfish",
        "scientific_name": "Semotilus corporalis",
        "biotope": "river",
        "stage": "forest_creek",
        "rarity": "common",
        "size_range": {"min": 15, "max": 45, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 1.5, "unit": "kg"},
        "base_value": 35,
        "xp_reward": 12,
        "description": "The largest native minnow in eastern North America.",
        "stats": {
            "strength": 3,
            "speed": 5,
            "stamina": 4,
            "fight_rating": "Easy-Medium"
        },
        "best_bait": ["worm", "crayfish", "fly"],
        "best_time": ["afternoon"],
        "season": ["spring", "summer"],
        "cooking_grade": "B",
        "flavor_profile": "Mild, firm",
        "icon": "🐟",
        "color": "#B8860B"
    },
    "redhorse_sucker": {
        "id": "redhorse_sucker",
        "name": "Golden Redhorse",
        "scientific_name": "Moxostoma erythrurum",
        "biotope": "river",
        "stage": "forest_creek",
        "rarity": "uncommon",
        "size_range": {"min": 25, "max": 60, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 3, "unit": "kg"},
        "base_value": 45,
        "xp_reward": 15,
        "description": "A bottom-feeder with fleshy, sucker-like lips.",
        "stats": {
            "strength": 4,
            "speed": 4,
            "stamina": 5,
            "fight_rating": "Medium"
        },
        "best_bait": ["worm", "dough_ball", "crayfish"],
        "best_time": ["spring"],
        "season": ["spring"],
        "cooking_grade": "B",
        "flavor_profile": "Sweet but bony",
        "icon": "🐟",
        "color": "#DAA520"
    },
    
    # LOWLAND RIVER (Stage 3) - 5 fish
    "channel_catfish": {
        "id": "channel_catfish",
        "name": "Channel Catfish",
        "scientific_name": "Ictalurus punctatus",
        "biotope": "river",
        "stage": "lowland_river",
        "rarity": "common",
        "size_range": {"min": 30, "max": 90, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 15, "unit": "kg"},
        "base_value": 65,
        "xp_reward": 22,
        "description": "America's most popular catfish species.",
        "stats": {
            "strength": 5,
            "speed": 3,
            "stamina": 6,
            "fight_rating": "Medium"
        },
        "best_bait": ["cut_bait", "chicken_liver", "stinkbait"],
        "best_time": ["night", "evening"],
        "season": ["spring", "summer"],
        "cooking_grade": "A+",
        "flavor_profile": "Mild, sweet, firm",
        "icon": "🐱",
        "color": "#4682B4"
    },
    "flathead_catfish": {
        "id": "flathead_catfish",
        "name": "Flathead Catfish",
        "scientific_name": "Pylodictis olivaris",
        "biotope": "river",
        "stage": "lowland_river",
        "rarity": "uncommon",
        "size_range": {"min": 40, "max": 130, "unit": "cm"},
        "weight_range": {"min": 1, "max": 50, "unit": "kg"},
        "base_value": 150,
        "xp_reward": 45,
        "description": "A nocturnal predator that prefers live prey.",
        "stats": {
            "strength": 8,
            "speed": 3,
            "stamina": 7,
            "fight_rating": "Hard"
        },
        "best_bait": ["live_fish", "large_minnow", "bluegill"],
        "best_time": ["night"],
        "season": ["summer"],
        "cooking_grade": "A+",
        "flavor_profile": "Best catfish, firm and sweet",
        "icon": "🐱",
        "color": "#8B7355"
    },
    "blue_catfish": {
        "id": "blue_catfish",
        "name": "Blue Catfish",
        "scientific_name": "Ictalurus furcatus",
        "biotope": "river",
        "stage": "lowland_river",
        "rarity": "uncommon",
        "size_range": {"min": 40, "max": 150, "unit": "cm"},
        "weight_range": {"min": 2, "max": 65, "unit": "kg"},
        "base_value": 130,
        "xp_reward": 40,
        "description": "The largest catfish species in North America.",
        "stats": {
            "strength": 7,
            "speed": 4,
            "stamina": 7,
            "fight_rating": "Hard"
        },
        "best_bait": ["cut_shad", "skipjack", "live_bait"],
        "best_time": ["evening", "night"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, firm, clean",
        "icon": "🐱",
        "color": "#4169E1"
    },
    "gar": {
        "id": "gar",
        "name": "Longnose Gar",
        "scientific_name": "Lepisosteus osseus",
        "biotope": "river",
        "stage": "lowland_river",
        "rarity": "uncommon",
        "size_range": {"min": 60, "max": 150, "unit": "cm"},
        "weight_range": {"min": 1, "max": 15, "unit": "kg"},
        "base_value": 80,
        "xp_reward": 28,
        "description": "An ancient fish with a long, toothy snout.",
        "stats": {
            "strength": 5,
            "speed": 6,
            "stamina": 5,
            "fight_rating": "Medium"
        },
        "best_bait": ["rope_lure", "minnow", "cut_bait"],
        "best_time": ["afternoon"],
        "season": ["summer"],
        "cooking_grade": "C",
        "flavor_profile": "Requires special preparation",
        "icon": "🐊",
        "color": "#556B2F"
    },
    "bowfin": {
        "id": "bowfin",
        "name": "Bowfin",
        "scientific_name": "Amia calva",
        "biotope": "river",
        "stage": "lowland_river",
        "rarity": "uncommon",
        "size_range": {"min": 40, "max": 90, "unit": "cm"},
        "weight_range": {"min": 1, "max": 10, "unit": "kg"},
        "base_value": 70,
        "xp_reward": 25,
        "description": "A living fossil with a prehistoric appearance.",
        "stats": {
            "strength": 6,
            "speed": 5,
            "stamina": 7,
            "fight_rating": "Hard"
        },
        "best_bait": ["cut_bait", "crayfish", "frog"],
        "best_time": ["morning", "evening"],
        "season": ["spring", "summer"],
        "cooking_grade": "C",
        "flavor_profile": "Soft texture, must be fresh",
        "icon": "🦴",
        "color": "#2F4F4F"
    },
    
    # RAPIDS (Stage 4) - 5 fish
    "steelhead": {
        "id": "steelhead",
        "name": "Steelhead Trout",
        "scientific_name": "Oncorhynchus mykiss",
        "biotope": "river",
        "stage": "rapids",
        "rarity": "rare",
        "size_range": {"min": 50, "max": 100, "unit": "cm"},
        "weight_range": {"min": 2, "max": 15, "unit": "kg"},
        "base_value": 250,
        "xp_reward": 70,
        "description": "Sea-run rainbow trout - a legendary fighter.",
        "stats": {
            "strength": 7,
            "speed": 8,
            "stamina": 7,
            "fight_rating": "Hard"
        },
        "best_bait": ["egg_pattern", "spey_fly", "spawn_sac"],
        "best_time": ["dawn", "dusk"],
        "season": ["fall", "winter", "spring"],
        "cooking_grade": "A++",
        "flavor_profile": "Rich, salmon-like, incredible",
        "icon": "🌟",
        "color": "#C0C0C0"
    },
    "atlantic_salmon": {
        "id": "atlantic_salmon",
        "name": "Atlantic Salmon",
        "scientific_name": "Salmo salar",
        "biotope": "river",
        "stage": "rapids",
        "rarity": "rare",
        "size_range": {"min": 50, "max": 120, "unit": "cm"},
        "weight_range": {"min": 3, "max": 20, "unit": "kg"},
        "base_value": 300,
        "xp_reward": 85,
        "description": "The 'King of Fish' - a prized game fish.",
        "stats": {
            "strength": 7,
            "speed": 8,
            "stamina": 8,
            "fight_rating": "Hard"
        },
        "best_bait": ["salmon_fly", "tube_fly", "bomber"],
        "best_time": ["morning", "evening"],
        "season": ["summer", "fall"],
        "cooking_grade": "A++",
        "flavor_profile": "Rich, buttery, pink flesh",
        "icon": "👑",
        "color": "#C0C0C0"
    },
    "chinook_salmon": {
        "id": "chinook_salmon",
        "name": "Chinook Salmon",
        "scientific_name": "Oncorhynchus tshawytscha",
        "biotope": "river",
        "stage": "rapids",
        "rarity": "rare",
        "size_range": {"min": 60, "max": 140, "unit": "cm"},
        "weight_range": {"min": 5, "max": 50, "unit": "kg"},
        "base_value": 350,
        "xp_reward": 95,
        "description": "The 'King Salmon' - largest Pacific salmon.",
        "stats": {
            "strength": 9,
            "speed": 7,
            "stamina": 8,
            "fight_rating": "Expert"
        },
        "best_bait": ["egg", "kwikfish", "spinner"],
        "best_time": ["dawn"],
        "season": ["fall"],
        "cooking_grade": "A++",
        "flavor_profile": "Rich, fatty, prized sushi fish",
        "icon": "👑",
        "color": "#2E8B57"
    },
    "coho_salmon": {
        "id": "coho_salmon",
        "name": "Coho Salmon",
        "scientific_name": "Oncorhynchus kisutch",
        "biotope": "river",
        "stage": "rapids",
        "rarity": "uncommon",
        "size_range": {"min": 45, "max": 85, "unit": "cm"},
        "weight_range": {"min": 2, "max": 12, "unit": "kg"},
        "base_value": 180,
        "xp_reward": 55,
        "description": "The 'Silver Salmon' - acrobatic and aggressive.",
        "stats": {
            "strength": 6,
            "speed": 8,
            "stamina": 6,
            "fight_rating": "Hard"
        },
        "best_bait": ["spinner", "spoon", "fly"],
        "best_time": ["morning"],
        "season": ["fall"],
        "cooking_grade": "A+",
        "flavor_profile": "Mild, orange flesh, versatile",
        "icon": "🐟",
        "color": "#C0C0C0"
    },
    "sockeye_salmon": {
        "id": "sockeye_salmon",
        "name": "Sockeye Salmon",
        "scientific_name": "Oncorhynchus nerka",
        "biotope": "river",
        "stage": "rapids",
        "rarity": "uncommon",
        "size_range": {"min": 45, "max": 75, "unit": "cm"},
        "weight_range": {"min": 2, "max": 7, "unit": "kg"},
        "base_value": 200,
        "xp_reward": 60,
        "description": "The 'Red Salmon' - deep red during spawn.",
        "stats": {
            "strength": 5,
            "speed": 7,
            "stamina": 6,
            "fight_rating": "Medium-Hard"
        },
        "best_bait": ["fly", "small_lure"],
        "best_time": ["midday"],
        "season": ["summer"],
        "cooking_grade": "A++",
        "flavor_profile": "Richest, reddest salmon meat",
        "icon": "🔴",
        "color": "#DC143C"
    },
    
    # MIGHTY RIVER (Stage 5) - 5 fish
    "white_sturgeon": {
        "id": "white_sturgeon",
        "name": "White Sturgeon",
        "scientific_name": "Acipenser transmontanus",
        "biotope": "river",
        "stage": "mighty_river",
        "rarity": "epic",
        "size_range": {"min": 150, "max": 500, "unit": "cm"},
        "weight_range": {"min": 50, "max": 600, "unit": "kg"},
        "base_value": 1000,
        "xp_reward": 250,
        "description": "North America's largest freshwater fish.",
        "stats": {
            "strength": 10,
            "speed": 4,
            "stamina": 10,
            "fight_rating": "Legendary"
        },
        "best_bait": ["lamprey", "eel", "smelt"],
        "best_time": ["dawn", "dusk"],
        "season": ["spring", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Firm, mild, caviar source",
        "icon": "🦴",
        "color": "#808080"
    },
    "pallid_sturgeon": {
        "id": "pallid_sturgeon",
        "name": "Pallid Sturgeon",
        "scientific_name": "Scaphirhynchus albus",
        "biotope": "river",
        "stage": "mighty_river",
        "rarity": "legendary",
        "size_range": {"min": 80, "max": 180, "unit": "cm"},
        "weight_range": {"min": 10, "max": 40, "unit": "kg"},
        "base_value": 2000,
        "xp_reward": 400,
        "description": "One of the rarest fish in North America.",
        "stats": {
            "strength": 7,
            "speed": 4,
            "stamina": 8,
            "fight_rating": "Hard"
        },
        "best_bait": ["worm", "minnow"],
        "best_time": ["any"],
        "season": ["spring"],
        "cooking_grade": "N/A",
        "flavor_profile": "Endangered - release immediately",
        "icon": "👻",
        "color": "#D3D3D3"
    },
    "paddlefish_river": {
        "id": "paddlefish_river",
        "name": "Paddlefish",
        "scientific_name": "Polyodon spathula",
        "biotope": "river",
        "stage": "mighty_river",
        "rarity": "rare",
        "size_range": {"min": 100, "max": 200, "unit": "cm"},
        "weight_range": {"min": 10, "max": 60, "unit": "kg"},
        "base_value": 400,
        "xp_reward": 110,
        "description": "An ancient fish with a paddle-shaped snout.",
        "stats": {
            "strength": 6,
            "speed": 5,
            "stamina": 7,
            "fight_rating": "Medium-Hard"
        },
        "best_bait": ["snagging_rig"],
        "best_time": ["spring"],
        "season": ["spring"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, valuable caviar",
        "icon": "🏓",
        "color": "#696969"
    },
    "blue_catfish_giant": {
        "id": "blue_catfish_giant",
        "name": "Giant Blue Catfish",
        "scientific_name": "Ictalurus furcatus",
        "biotope": "river",
        "stage": "mighty_river",
        "rarity": "epic",
        "size_range": {"min": 100, "max": 170, "unit": "cm"},
        "weight_range": {"min": 30, "max": 70, "unit": "kg"},
        "base_value": 500,
        "xp_reward": 140,
        "description": "A trophy-sized blue cat from deep river channels.",
        "stats": {
            "strength": 9,
            "speed": 4,
            "stamina": 9,
            "fight_rating": "Hard"
        },
        "best_bait": ["large_shad", "skipjack", "drum"],
        "best_time": ["night"],
        "season": ["spring", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Firm, clean, excellent",
        "icon": "🐱",
        "color": "#1E3A5F"
    },
    "alligator_gar_river": {
        "id": "alligator_gar_river",
        "name": "Alligator Gar",
        "scientific_name": "Atractosteus spatula",
        "biotope": "river",
        "stage": "mighty_river",
        "rarity": "epic",
        "size_range": {"min": 150, "max": 300, "unit": "cm"},
        "weight_range": {"min": 30, "max": 140, "unit": "kg"},
        "base_value": 600,
        "xp_reward": 160,
        "description": "The largest gar species - a true river monster.",
        "stats": {
            "strength": 9,
            "speed": 6,
            "stamina": 8,
            "fight_rating": "Expert"
        },
        "best_bait": ["large_fish", "rope_fly", "cut_carp"],
        "best_time": ["morning", "evening"],
        "season": ["summer"],
        "cooking_grade": "B",
        "flavor_profile": "Firm white meat, requires preparation",
        "icon": "🐊",
        "color": "#3D5A3D"
    }
}
