# ========== GO FISH! BIOTOPE FISH DATABASE - BRACKISH WATER ==========
# 25 Brackish Water Fish Species
# ~500+ lines of backend code

BRACKISH_FISH = {
    # TIDAL MARSH (Stage 1) - 5 fish
    "redfish": {
        "id": "redfish",
        "name": "Red Drum",
        "scientific_name": "Sciaenops ocellatus",
        "biotope": "brackish",
        "stage": "tidal_marsh",
        "rarity": "common",
        "size_range": {"min": 35, "max": 100, "unit": "cm"},
        "weight_range": {"min": 1, "max": 25, "unit": "kg"},
        "base_value": 90,
        "xp_reward": 30,
        "description": "A bronze beauty with a distinctive tail spot.",
        "stats": {
            "strength": 6,
            "speed": 5,
            "stamina": 6,
            "fight_rating": "Medium-Hard"
        },
        "best_bait": ["shrimp", "crab", "cut_mullet"],
        "best_time": ["dawn", "dusk", "changing_tide"],
        "season": ["fall", "winter", "spring"],
        "cooking_grade": "A+",
        "flavor_profile": "Mild, sweet, firm",
        "icon": "🐟",
        "color": "#CD853F"
    },
    "spotted_seatrout": {
        "id": "spotted_seatrout",
        "name": "Spotted Seatrout",
        "scientific_name": "Cynoscion nebulosus",
        "biotope": "brackish",
        "stage": "tidal_marsh",
        "rarity": "common",
        "size_range": {"min": 30, "max": 75, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 7, "unit": "kg"},
        "base_value": 80,
        "xp_reward": 28,
        "description": "A speckled predator of the shallows.",
        "stats": {
            "strength": 4,
            "speed": 6,
            "stamina": 4,
            "fight_rating": "Medium"
        },
        "best_bait": ["shrimp", "mirrolure", "soft_plastic"],
        "best_time": ["dawn", "dusk"],
        "season": ["spring", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, delicate, flaky",
        "icon": "🐟",
        "color": "#708090"
    },
    "sheepshead": {
        "id": "sheepshead",
        "name": "Sheepshead",
        "scientific_name": "Archosargus probatocephalus",
        "biotope": "brackish",
        "stage": "tidal_marsh",
        "rarity": "common",
        "size_range": {"min": 25, "max": 60, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 8, "unit": "kg"},
        "base_value": 75,
        "xp_reward": 25,
        "description": "Known for human-like teeth that crush shellfish.",
        "stats": {
            "strength": 5,
            "speed": 3,
            "stamina": 5,
            "fight_rating": "Medium"
        },
        "best_bait": ["fiddler_crab", "shrimp", "barnacle"],
        "best_time": ["incoming_tide"],
        "season": ["winter", "spring"],
        "cooking_grade": "A+",
        "flavor_profile": "Sweet, shellfish-flavored, firm",
        "icon": "🐑",
        "color": "#2F4F4F"
    },
    "black_drum": {
        "id": "black_drum",
        "name": "Black Drum",
        "scientific_name": "Pogonias cromis",
        "biotope": "brackish",
        "stage": "tidal_marsh",
        "rarity": "uncommon",
        "size_range": {"min": 35, "max": 120, "unit": "cm"},
        "weight_range": {"min": 1, "max": 45, "unit": "kg"},
        "base_value": 120,
        "xp_reward": 40,
        "description": "A powerful bottom feeder that produces drumming sounds.",
        "stats": {
            "strength": 7,
            "speed": 3,
            "stamina": 7,
            "fight_rating": "Medium-Hard"
        },
        "best_bait": ["crab", "clam", "shrimp"],
        "best_time": ["changing_tide"],
        "season": ["winter", "spring"],
        "cooking_grade": "B+",
        "flavor_profile": "Mild, firm, best when small",
        "icon": "🥁",
        "color": "#2F2F2F"
    },
    "flounder_brackish": {
        "id": "flounder_brackish",
        "name": "Southern Flounder",
        "scientific_name": "Paralichthys lethostigma",
        "biotope": "brackish",
        "stage": "tidal_marsh",
        "rarity": "common",
        "size_range": {"min": 30, "max": 70, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 9, "unit": "kg"},
        "base_value": 85,
        "xp_reward": 28,
        "description": "A flatfish ambush predator of muddy bottoms.",
        "stats": {
            "strength": 3,
            "speed": 5,
            "stamina": 4,
            "fight_rating": "Easy-Medium"
        },
        "best_bait": ["mud_minnow", "shrimp", "finger_mullet"],
        "best_time": ["outgoing_tide"],
        "season": ["fall"],
        "cooking_grade": "A++",
        "flavor_profile": "Delicate, sweet, buttery",
        "icon": "🐟",
        "color": "#8B7355"
    },
    
    # MANGROVE FOREST (Stage 2) - 5 fish
    "snook": {
        "id": "snook",
        "name": "Common Snook",
        "scientific_name": "Centropomus undecimalis",
        "biotope": "brackish",
        "stage": "mangrove_forest",
        "rarity": "uncommon",
        "size_range": {"min": 40, "max": 120, "unit": "cm"},
        "weight_range": {"min": 1, "max": 25, "unit": "kg"},
        "base_value": 180,
        "xp_reward": 55,
        "description": "The 'linesider' - a prized inshore game fish.",
        "stats": {
            "strength": 7,
            "speed": 8,
            "stamina": 6,
            "fight_rating": "Hard"
        },
        "best_bait": ["pilchard", "shrimp", "soft_plastic"],
        "best_time": ["dawn", "dusk", "night"],
        "season": ["spring", "summer"],
        "cooking_grade": "A+",
        "flavor_profile": "Mild, white, delicate",
        "icon": "🐟",
        "color": "#708090"
    },
    "tarpon": {
        "id": "tarpon",
        "name": "Atlantic Tarpon",
        "scientific_name": "Megalops atlanticus",
        "biotope": "brackish",
        "stage": "mangrove_forest",
        "rarity": "rare",
        "size_range": {"min": 100, "max": 250, "unit": "cm"},
        "weight_range": {"min": 20, "max": 130, "unit": "kg"},
        "base_value": 400,
        "xp_reward": 100,
        "description": "The 'Silver King' - legendary for aerial acrobatics.",
        "stats": {
            "strength": 9,
            "speed": 8,
            "stamina": 8,
            "fight_rating": "Expert"
        },
        "best_bait": ["crab", "mullet", "large_fly"],
        "best_time": ["dawn", "dusk"],
        "season": ["spring", "summer"],
        "cooking_grade": "C",
        "flavor_profile": "Bony, usually released",
        "icon": "👑",
        "color": "#C0C0C0"
    },
    "mangrove_snapper": {
        "id": "mangrove_snapper",
        "name": "Mangrove Snapper",
        "scientific_name": "Lutjanus griseus",
        "biotope": "brackish",
        "stage": "mangrove_forest",
        "rarity": "common",
        "size_range": {"min": 20, "max": 60, "unit": "cm"},
        "weight_range": {"min": 0.3, "max": 8, "unit": "kg"},
        "base_value": 100,
        "xp_reward": 35,
        "description": "A wary snapper found among mangrove roots.",
        "stats": {
            "strength": 4,
            "speed": 5,
            "stamina": 5,
            "fight_rating": "Medium"
        },
        "best_bait": ["shrimp", "pilchard", "cut_bait"],
        "best_time": ["dawn", "dusk"],
        "season": ["all"],
        "cooking_grade": "A+",
        "flavor_profile": "Sweet, firm, excellent",
        "icon": "🐟",
        "color": "#808080"
    },
    "jack_crevalle": {
        "id": "jack_crevalle",
        "name": "Jack Crevalle",
        "scientific_name": "Caranx hippos",
        "biotope": "brackish",
        "stage": "mangrove_forest",
        "rarity": "common",
        "size_range": {"min": 30, "max": 100, "unit": "cm"},
        "weight_range": {"min": 1, "max": 25, "unit": "kg"},
        "base_value": 70,
        "xp_reward": 25,
        "description": "A powerful, aggressive predator.",
        "stats": {
            "strength": 8,
            "speed": 7,
            "stamina": 7,
            "fight_rating": "Hard"
        },
        "best_bait": ["topwater", "spoon", "live_bait"],
        "best_time": ["morning"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "C",
        "flavor_profile": "Strong, dark meat, acquired taste",
        "icon": "💪",
        "color": "#FFD700"
    },
    "ladyfish": {
        "id": "ladyfish",
        "name": "Ladyfish",
        "scientific_name": "Elops saurus",
        "biotope": "brackish",
        "stage": "mangrove_forest",
        "rarity": "common",
        "size_range": {"min": 30, "max": 90, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 7, "unit": "kg"},
        "base_value": 40,
        "xp_reward": 15,
        "description": "A silvery acrobat that fights above its weight.",
        "stats": {
            "strength": 4,
            "speed": 8,
            "stamina": 4,
            "fight_rating": "Medium"
        },
        "best_bait": ["small_lure", "fly", "shrimp"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "D",
        "flavor_profile": "Very bony, usually released",
        "icon": "👸",
        "color": "#E0E0E0"
    },
    
    # ESTUARY (Stage 3) - 5 fish
    "striped_bass_brackish": {
        "id": "striped_bass_brackish",
        "name": "Striped Bass",
        "scientific_name": "Morone saxatilis",
        "biotope": "brackish",
        "stage": "estuary",
        "rarity": "uncommon",
        "size_range": {"min": 40, "max": 120, "unit": "cm"},
        "weight_range": {"min": 2, "max": 30, "unit": "kg"},
        "base_value": 150,
        "xp_reward": 50,
        "description": "Migratory stripers moving through estuaries.",
        "stats": {
            "strength": 7,
            "speed": 6,
            "stamina": 7,
            "fight_rating": "Hard"
        },
        "best_bait": ["bunker", "eel", "soft_plastic"],
        "best_time": ["changing_tide", "night"],
        "season": ["spring", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, firm, versatile",
        "icon": "🐟",
        "color": "#696969"
    },
    "white_perch": {
        "id": "white_perch",
        "name": "White Perch",
        "scientific_name": "Morone americana",
        "biotope": "brackish",
        "stage": "estuary",
        "rarity": "common",
        "size_range": {"min": 15, "max": 35, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 1.5, "unit": "kg"},
        "base_value": 35,
        "xp_reward": 12,
        "description": "A schooling fish that tolerates varying salinity.",
        "stats": {
            "strength": 2,
            "speed": 4,
            "stamina": 3,
            "fight_rating": "Easy"
        },
        "best_bait": ["worm", "minnow", "small_jig"],
        "best_time": ["any"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, sweet, panfish",
        "icon": "🐟",
        "color": "#C0C0C0"
    },
    "blue_crab_fish": {
        "id": "blue_crab_fish",
        "name": "Cobia",
        "scientific_name": "Rachycentron canadum",
        "biotope": "brackish",
        "stage": "estuary",
        "rarity": "rare",
        "size_range": {"min": 60, "max": 180, "unit": "cm"},
        "weight_range": {"min": 5, "max": 60, "unit": "kg"},
        "base_value": 300,
        "xp_reward": 80,
        "description": "A powerful fish often found near rays and sharks.",
        "stats": {
            "strength": 8,
            "speed": 6,
            "stamina": 7,
            "fight_rating": "Hard"
        },
        "best_bait": ["crab", "eel", "live_fish"],
        "best_time": ["morning"],
        "season": ["spring", "summer"],
        "cooking_grade": "A+",
        "flavor_profile": "Firm, rich, versatile",
        "icon": "🐟",
        "color": "#4A4A4A"
    },
    "atlantic_croaker": {
        "id": "atlantic_croaker",
        "name": "Atlantic Croaker",
        "scientific_name": "Micropogonias undulatus",
        "biotope": "brackish",
        "stage": "estuary",
        "rarity": "common",
        "size_range": {"min": 20, "max": 45, "unit": "cm"},
        "weight_range": {"min": 0.2, "max": 2, "unit": "kg"},
        "base_value": 45,
        "xp_reward": 15,
        "description": "Named for the croaking sound it makes.",
        "stats": {
            "strength": 2,
            "speed": 3,
            "stamina": 3,
            "fight_rating": "Easy"
        },
        "best_bait": ["shrimp", "bloodworm", "squid"],
        "best_time": ["any"],
        "season": ["summer", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, sweet, firm",
        "icon": "🐸",
        "color": "#FFD700"
    },
    "weakfish": {
        "id": "weakfish",
        "name": "Weakfish",
        "scientific_name": "Cynoscion regalis",
        "biotope": "brackish",
        "stage": "estuary",
        "rarity": "uncommon",
        "size_range": {"min": 30, "max": 75, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 8, "unit": "kg"},
        "base_value": 90,
        "xp_reward": 30,
        "description": "Named for its fragile mouth tissue.",
        "stats": {
            "strength": 4,
            "speed": 5,
            "stamina": 4,
            "fight_rating": "Medium"
        },
        "best_bait": ["shrimp", "sandworm", "soft_plastic"],
        "best_time": ["dawn", "dusk"],
        "season": ["spring", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Sweet, delicate, flaky",
        "icon": "🐟",
        "color": "#9370DB"
    },
    
    # COASTAL LAGOON (Stage 4) - 5 fish
    "bonefish_brackish": {
        "id": "bonefish_brackish",
        "name": "Bonefish",
        "scientific_name": "Albula vulpes",
        "biotope": "brackish",
        "stage": "coastal_lagoon",
        "rarity": "rare",
        "size_range": {"min": 35, "max": 75, "unit": "cm"},
        "weight_range": {"min": 1, "max": 9, "unit": "kg"},
        "base_value": 250,
        "xp_reward": 70,
        "description": "The 'Grey Ghost' - fastest fish on the flats.",
        "stats": {
            "strength": 6,
            "speed": 10,
            "stamina": 7,
            "fight_rating": "Hard"
        },
        "best_bait": ["shrimp_fly", "crab_fly", "small_crab"],
        "best_time": ["incoming_tide"],
        "season": ["winter", "spring"],
        "cooking_grade": "C",
        "flavor_profile": "Bony, usually released",
        "icon": "👻",
        "color": "#C0C0C0"
    },
    "permit_brackish": {
        "id": "permit_brackish",
        "name": "Permit",
        "scientific_name": "Trachinotus falcatus",
        "biotope": "brackish",
        "stage": "coastal_lagoon",
        "rarity": "rare",
        "size_range": {"min": 35, "max": 90, "unit": "cm"},
        "weight_range": {"min": 1, "max": 20, "unit": "kg"},
        "base_value": 300,
        "xp_reward": 85,
        "description": "One of the most challenging flats fish to catch.",
        "stats": {
            "strength": 7,
            "speed": 8,
            "stamina": 7,
            "fight_rating": "Hard"
        },
        "best_bait": ["crab", "crab_fly", "shrimp"],
        "best_time": ["incoming_tide"],
        "season": ["spring", "summer"],
        "cooking_grade": "A",
        "flavor_profile": "Excellent, similar to pompano",
        "icon": "🐟",
        "color": "#C0C0C0"
    },
    "barramundi": {
        "id": "barramundi",
        "name": "Barramundi",
        "scientific_name": "Lates calcarifer",
        "biotope": "brackish",
        "stage": "coastal_lagoon",
        "rarity": "uncommon",
        "size_range": {"min": 50, "max": 150, "unit": "cm"},
        "weight_range": {"min": 3, "max": 40, "unit": "kg"},
        "base_value": 200,
        "xp_reward": 60,
        "description": "Australia's premier sportfish.",
        "stats": {
            "strength": 7,
            "speed": 6,
            "stamina": 6,
            "fight_rating": "Hard"
        },
        "best_bait": ["mullet", "prawn", "lure"],
        "best_time": ["dawn", "dusk"],
        "season": ["wet_season"],
        "cooking_grade": "A++",
        "flavor_profile": "Mild, buttery, moist",
        "icon": "🐟",
        "color": "#808080"
    },
    "mulloway": {
        "id": "mulloway",
        "name": "Mulloway",
        "scientific_name": "Argyrosomus japonicus",
        "biotope": "brackish",
        "stage": "coastal_lagoon",
        "rarity": "uncommon",
        "size_range": {"min": 40, "max": 150, "unit": "cm"},
        "weight_range": {"min": 2, "max": 45, "unit": "kg"},
        "base_value": 180,
        "xp_reward": 55,
        "description": "Also called jewfish, a prized Australian species.",
        "stats": {
            "strength": 6,
            "speed": 5,
            "stamina": 6,
            "fight_rating": "Medium-Hard"
        },
        "best_bait": ["mullet", "squid", "soft_plastic"],
        "best_time": ["night", "dusk"],
        "season": ["summer", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, moist, flaky",
        "icon": "💎",
        "color": "#C0C0C0"
    },
    "giant_trevally": {
        "id": "giant_trevally",
        "name": "Giant Trevally",
        "scientific_name": "Caranx ignobilis",
        "biotope": "brackish",
        "stage": "coastal_lagoon",
        "rarity": "rare",
        "size_range": {"min": 60, "max": 170, "unit": "cm"},
        "weight_range": {"min": 5, "max": 80, "unit": "kg"},
        "base_value": 350,
        "xp_reward": 95,
        "description": "The GT - an apex predator of tropical waters.",
        "stats": {
            "strength": 10,
            "speed": 9,
            "stamina": 8,
            "fight_rating": "Expert"
        },
        "best_bait": ["popper", "stickbait", "large_fly"],
        "best_time": ["dawn", "dusk"],
        "season": ["all"],
        "cooking_grade": "B",
        "flavor_profile": "Firm, strong, best when small",
        "icon": "💪",
        "color": "#2F4F4F"
    },
    
    # DELTA (Stage 5) - 5 fish
    "nile_perch": {
        "id": "nile_perch",
        "name": "Nile Perch",
        "scientific_name": "Lates niloticus",
        "biotope": "brackish",
        "stage": "delta",
        "rarity": "epic",
        "size_range": {"min": 80, "max": 200, "unit": "cm"},
        "weight_range": {"min": 10, "max": 200, "unit": "kg"},
        "base_value": 600,
        "xp_reward": 150,
        "description": "One of the largest freshwater fish in the world.",
        "stats": {
            "strength": 9,
            "speed": 5,
            "stamina": 8,
            "fight_rating": "Hard"
        },
        "best_bait": ["large_fish", "lure", "cut_bait"],
        "best_time": ["morning", "evening"],
        "season": ["all"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, white, firm",
        "icon": "👑",
        "color": "#808080"
    },
    "goliath_grouper": {
        "id": "goliath_grouper",
        "name": "Goliath Grouper",
        "scientific_name": "Epinephelus itajara",
        "biotope": "brackish",
        "stage": "delta",
        "rarity": "epic",
        "size_range": {"min": 100, "max": 250, "unit": "cm"},
        "weight_range": {"min": 50, "max": 360, "unit": "kg"},
        "base_value": 800,
        "xp_reward": 200,
        "description": "A massive, protected grouper species.",
        "stats": {
            "strength": 10,
            "speed": 3,
            "stamina": 10,
            "fight_rating": "Legendary"
        },
        "best_bait": ["large_fish", "crab", "lobster"],
        "best_time": ["any"],
        "season": ["summer"],
        "cooking_grade": "N/A",
        "flavor_profile": "Protected - catch & release only",
        "icon": "🏋️",
        "color": "#556B2F"
    },
    "sawfish": {
        "id": "sawfish",
        "name": "Largetooth Sawfish",
        "scientific_name": "Pristis pristis",
        "biotope": "brackish",
        "stage": "delta",
        "rarity": "legendary",
        "size_range": {"min": 200, "max": 600, "unit": "cm"},
        "weight_range": {"min": 100, "max": 500, "unit": "kg"},
        "base_value": 2000,
        "xp_reward": 400,
        "description": "A critically endangered ray with saw-like snout.",
        "stats": {
            "strength": 9,
            "speed": 4,
            "stamina": 8,
            "fight_rating": "Legendary"
        },
        "best_bait": ["fish"],
        "best_time": ["night"],
        "season": ["all"],
        "cooking_grade": "N/A",
        "flavor_profile": "Critically endangered - release immediately",
        "icon": "🪚",
        "color": "#8B7355"
    },
    "bull_shark": {
        "id": "bull_shark",
        "name": "Bull Shark",
        "scientific_name": "Carcharhinus leucas",
        "biotope": "brackish",
        "stage": "delta",
        "rarity": "rare",
        "size_range": {"min": 150, "max": 340, "unit": "cm"},
        "weight_range": {"min": 50, "max": 230, "unit": "kg"},
        "base_value": 500,
        "xp_reward": 130,
        "description": "The only shark that thrives in freshwater.",
        "stats": {
            "strength": 10,
            "speed": 7,
            "stamina": 8,
            "fight_rating": "Expert"
        },
        "best_bait": ["large_fish", "bloody_chunk"],
        "best_time": ["dusk", "dawn"],
        "season": ["summer"],
        "cooking_grade": "B",
        "flavor_profile": "Firm, mild when prepared properly",
        "icon": "🦈",
        "color": "#696969"
    },
    "giant_stingray": {
        "id": "giant_stingray",
        "name": "Giant Freshwater Stingray",
        "scientific_name": "Urogymnus polylepis",
        "biotope": "brackish",
        "stage": "delta",
        "rarity": "legendary",
        "size_range": {"min": 200, "max": 400, "unit": "cm"},
        "weight_range": {"min": 100, "max": 600, "unit": "kg"},
        "base_value": 1500,
        "xp_reward": 350,
        "description": "Possibly the world's largest freshwater fish.",
        "stats": {
            "strength": 10,
            "speed": 3,
            "stamina": 10,
            "fight_rating": "Legendary"
        },
        "best_bait": ["fish", "clam"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "N/A",
        "flavor_profile": "Protected species - release only",
        "icon": "🦂",
        "color": "#8B4513"
    }
}
