# ========== GO FISH! BIOTOPE FISH DATABASE - SALTWATER ==========
# 25 Salt Sea Fish Species
# ~500+ lines of backend code

SALTWATER_FISH = {
    # COASTAL SHALLOWS (Stage 1) - 5 fish
    "sea_bass": {
        "id": "sea_bass",
        "name": "Sea Bass",
        "scientific_name": "Centropristis striata",
        "biotope": "saltwater",
        "stage": "coastal_shallows",
        "rarity": "common",
        "size_range": {"min": 30, "max": 60, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 4, "unit": "kg"},
        "base_value": 45,
        "xp_reward": 15,
        "description": "A popular game fish found along rocky coastlines.",
        "stats": {
            "strength": 3,
            "speed": 3,
            "stamina": 4,
            "fight_rating": "Medium"
        },
        "best_bait": ["shrimp", "squid", "crab"],
        "best_time": ["dawn", "dusk"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, sweet, flaky",
        "icon": "🐟",
        "color": "#4682B4"
    },
    "flounder": {
        "id": "flounder",
        "name": "Summer Flounder",
        "scientific_name": "Paralichthys dentatus",
        "biotope": "saltwater",
        "stage": "coastal_shallows",
        "rarity": "common",
        "size_range": {"min": 35, "max": 75, "unit": "cm"},
        "weight_range": {"min": 1, "max": 6, "unit": "kg"},
        "base_value": 55,
        "xp_reward": 18,
        "description": "A flat fish that ambushes prey from the sandy bottom.",
        "stats": {
            "strength": 2,
            "speed": 4,
            "stamina": 3,
            "fight_rating": "Easy"
        },
        "best_bait": ["minnow", "squid", "shrimp"],
        "best_time": ["changing_tide"],
        "season": ["summer", "fall"],
        "cooking_grade": "A+",
        "flavor_profile": "Delicate, sweet, firm",
        "icon": "🐟",
        "color": "#8B7355"
    },
    "bluefish": {
        "id": "bluefish",
        "name": "Bluefish",
        "scientific_name": "Pomatomus saltatrix",
        "biotope": "saltwater",
        "stage": "coastal_shallows",
        "rarity": "common",
        "size_range": {"min": 40, "max": 90, "unit": "cm"},
        "weight_range": {"min": 1, "max": 9, "unit": "kg"},
        "base_value": 50,
        "xp_reward": 20,
        "description": "An aggressive predator known for its sharp teeth.",
        "stats": {
            "strength": 5,
            "speed": 5,
            "stamina": 4,
            "fight_rating": "Hard"
        },
        "best_bait": ["bunker", "mackerel", "metal_lure"],
        "best_time": ["morning", "evening"],
        "season": ["summer", "fall"],
        "cooking_grade": "B",
        "flavor_profile": "Rich, oily, strong",
        "icon": "🐟",
        "color": "#4169E1"
    },
    "striped_bass": {
        "id": "striped_bass",
        "name": "Striped Bass",
        "scientific_name": "Morone saxatilis",
        "biotope": "saltwater",
        "stage": "coastal_shallows",
        "rarity": "uncommon",
        "size_range": {"min": 45, "max": 120, "unit": "cm"},
        "weight_range": {"min": 2, "max": 25, "unit": "kg"},
        "base_value": 120,
        "xp_reward": 35,
        "description": "The king of coastal game fish with iconic stripes.",
        "stats": {
            "strength": 6,
            "speed": 5,
            "stamina": 6,
            "fight_rating": "Hard"
        },
        "best_bait": ["bunker", "eel", "clam"],
        "best_time": ["dawn", "dusk", "night"],
        "season": ["spring", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, firm, versatile",
        "icon": "🐟",
        "color": "#708090"
    },
    "pompano": {
        "id": "pompano",
        "name": "Florida Pompano",
        "scientific_name": "Trachinotus carolinus",
        "biotope": "saltwater",
        "stage": "coastal_shallows",
        "rarity": "uncommon",
        "size_range": {"min": 25, "max": 45, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 3.5, "unit": "kg"},
        "base_value": 150,
        "xp_reward": 40,
        "description": "A prized table fish with silvery, compressed body.",
        "stats": {
            "strength": 4,
            "speed": 6,
            "stamina": 4,
            "fight_rating": "Medium"
        },
        "best_bait": ["sand_flea", "shrimp", "clam"],
        "best_time": ["incoming_tide"],
        "season": ["spring", "fall", "winter"],
        "cooking_grade": "A++",
        "flavor_profile": "Sweet, rich, buttery",
        "icon": "🐟",
        "color": "#C0C0C0"
    },
    
    # CORAL REEF (Stage 2) - 5 fish
    "parrotfish": {
        "id": "parrotfish",
        "name": "Rainbow Parrotfish",
        "scientific_name": "Scarus guacamaia",
        "biotope": "saltwater",
        "stage": "coral_reef",
        "rarity": "common",
        "size_range": {"min": 40, "max": 100, "unit": "cm"},
        "weight_range": {"min": 2, "max": 20, "unit": "kg"},
        "base_value": 75,
        "xp_reward": 25,
        "description": "A colorful reef fish that creates sand from coral.",
        "stats": {
            "strength": 4,
            "speed": 3,
            "stamina": 5,
            "fight_rating": "Medium"
        },
        "best_bait": ["small_crab", "seaweed_bait"],
        "best_time": ["midday"],
        "season": ["all"],
        "cooking_grade": "B",
        "flavor_profile": "Mild, slightly sweet",
        "icon": "🦜",
        "color": "#00CED1"
    },
    "grouper": {
        "id": "grouper",
        "name": "Red Grouper",
        "scientific_name": "Epinephelus morio",
        "biotope": "saltwater",
        "stage": "coral_reef",
        "rarity": "uncommon",
        "size_range": {"min": 40, "max": 100, "unit": "cm"},
        "weight_range": {"min": 2, "max": 23, "unit": "kg"},
        "base_value": 180,
        "xp_reward": 50,
        "description": "A heavy-bodied reef dweller prized for its meat.",
        "stats": {
            "strength": 7,
            "speed": 2,
            "stamina": 6,
            "fight_rating": "Hard"
        },
        "best_bait": ["squid", "pinfish", "sardine"],
        "best_time": ["morning", "afternoon"],
        "season": ["all"],
        "cooking_grade": "A+",
        "flavor_profile": "Mild, sweet, firm",
        "icon": "🐟",
        "color": "#CD5C5C"
    },
    "snapper": {
        "id": "snapper",
        "name": "Red Snapper",
        "scientific_name": "Lutjanus campechanus",
        "biotope": "saltwater",
        "stage": "coral_reef",
        "rarity": "uncommon",
        "size_range": {"min": 35, "max": 90, "unit": "cm"},
        "weight_range": {"min": 1, "max": 15, "unit": "kg"},
        "base_value": 200,
        "xp_reward": 55,
        "description": "One of the most sought-after reef fish.",
        "stats": {
            "strength": 5,
            "speed": 4,
            "stamina": 5,
            "fight_rating": "Medium-Hard"
        },
        "best_bait": ["squid", "cigar_minnow", "cut_fish"],
        "best_time": ["dawn", "dusk"],
        "season": ["all"],
        "cooking_grade": "A++",
        "flavor_profile": "Nutty, sweet, moist",
        "icon": "🐟",
        "color": "#FF6347"
    },
    "triggerfish": {
        "id": "triggerfish",
        "name": "Gray Triggerfish",
        "scientific_name": "Balistes capriscus",
        "biotope": "saltwater",
        "stage": "coral_reef",
        "rarity": "common",
        "size_range": {"min": 25, "max": 55, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 6, "unit": "kg"},
        "base_value": 85,
        "xp_reward": 28,
        "description": "A tough-skinned fish with powerful jaws.",
        "stats": {
            "strength": 4,
            "speed": 3,
            "stamina": 6,
            "fight_rating": "Medium"
        },
        "best_bait": ["squid", "shrimp", "cut_fish"],
        "best_time": ["afternoon"],
        "season": ["summer", "fall"],
        "cooking_grade": "A",
        "flavor_profile": "Sweet, firm, crab-like",
        "icon": "🐟",
        "color": "#696969"
    },
    "barracuda": {
        "id": "barracuda",
        "name": "Great Barracuda",
        "scientific_name": "Sphyraena barracuda",
        "biotope": "saltwater",
        "stage": "coral_reef",
        "rarity": "rare",
        "size_range": {"min": 60, "max": 180, "unit": "cm"},
        "weight_range": {"min": 3, "max": 50, "unit": "kg"},
        "base_value": 250,
        "xp_reward": 70,
        "description": "A fearsome predator with razor-sharp teeth.",
        "stats": {
            "strength": 7,
            "speed": 9,
            "stamina": 5,
            "fight_rating": "Hard"
        },
        "best_bait": ["tube_lure", "needlefish", "ballyhoo"],
        "best_time": ["morning"],
        "season": ["all"],
        "cooking_grade": "C",
        "flavor_profile": "Strong, requires preparation",
        "icon": "🦈",
        "color": "#2F4F4F"
    },
    
    # OPEN OCEAN (Stage 3) - 5 fish
    "yellowfin_tuna": {
        "id": "yellowfin_tuna",
        "name": "Yellowfin Tuna",
        "scientific_name": "Thunnus albacares",
        "biotope": "saltwater",
        "stage": "open_ocean",
        "rarity": "uncommon",
        "size_range": {"min": 80, "max": 200, "unit": "cm"},
        "weight_range": {"min": 10, "max": 180, "unit": "kg"},
        "base_value": 400,
        "xp_reward": 100,
        "description": "A powerful pelagic fish prized by sport fishers.",
        "stats": {
            "strength": 9,
            "speed": 10,
            "stamina": 8,
            "fight_rating": "Expert"
        },
        "best_bait": ["squid", "flying_fish", "cedar_plug"],
        "best_time": ["dawn", "dusk"],
        "season": ["summer", "fall"],
        "cooking_grade": "A++",
        "flavor_profile": "Rich, meaty, sashimi-grade",
        "icon": "🐟",
        "color": "#FFD700"
    },
    "mahi_mahi": {
        "id": "mahi_mahi",
        "name": "Mahi-Mahi",
        "scientific_name": "Coryphaena hippurus",
        "biotope": "saltwater",
        "stage": "open_ocean",
        "rarity": "uncommon",
        "size_range": {"min": 60, "max": 140, "unit": "cm"},
        "weight_range": {"min": 5, "max": 30, "unit": "kg"},
        "base_value": 280,
        "xp_reward": 75,
        "description": "Also known as Dolphinfish, famous for acrobatic fights.",
        "stats": {
            "strength": 7,
            "speed": 8,
            "stamina": 6,
            "fight_rating": "Hard"
        },
        "best_bait": ["ballyhoo", "squid", "feather_lure"],
        "best_time": ["morning"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "A+",
        "flavor_profile": "Mild, sweet, firm",
        "icon": "🐟",
        "color": "#32CD32"
    },
    "wahoo": {
        "id": "wahoo",
        "name": "Wahoo",
        "scientific_name": "Acanthocybium solandri",
        "biotope": "saltwater",
        "stage": "open_ocean",
        "rarity": "rare",
        "size_range": {"min": 100, "max": 200, "unit": "cm"},
        "weight_range": {"min": 10, "max": 80, "unit": "kg"},
        "base_value": 350,
        "xp_reward": 90,
        "description": "One of the fastest fish in the ocean.",
        "stats": {
            "strength": 8,
            "speed": 10,
            "stamina": 5,
            "fight_rating": "Hard"
        },
        "best_bait": ["high_speed_lure", "ballyhoo", "bonito"],
        "best_time": ["morning", "afternoon"],
        "season": ["summer", "fall"],
        "cooking_grade": "A+",
        "flavor_profile": "Delicate, white, flaky",
        "icon": "🐟",
        "color": "#4169E1"
    },
    "sailfish": {
        "id": "sailfish",
        "name": "Atlantic Sailfish",
        "scientific_name": "Istiophorus albicans",
        "biotope": "saltwater",
        "stage": "open_ocean",
        "rarity": "rare",
        "size_range": {"min": 180, "max": 300, "unit": "cm"},
        "weight_range": {"min": 25, "max": 60, "unit": "kg"},
        "base_value": 500,
        "xp_reward": 120,
        "description": "The fastest fish in the ocean with spectacular sail.",
        "stats": {
            "strength": 8,
            "speed": 10,
            "stamina": 7,
            "fight_rating": "Expert"
        },
        "best_bait": ["ballyhoo", "goggle_eye", "strip_bait"],
        "best_time": ["morning"],
        "season": ["winter", "spring"],
        "cooking_grade": "B",
        "flavor_profile": "Gamey, best released",
        "icon": "⛵",
        "color": "#1E90FF"
    },
    "king_mackerel": {
        "id": "king_mackerel",
        "name": "King Mackerel",
        "scientific_name": "Scomberomorus cavalla",
        "biotope": "saltwater",
        "stage": "open_ocean",
        "rarity": "common",
        "size_range": {"min": 60, "max": 150, "unit": "cm"},
        "weight_range": {"min": 3, "max": 40, "unit": "kg"},
        "base_value": 180,
        "xp_reward": 55,
        "description": "A fast, fierce fighter popular with anglers.",
        "stats": {
            "strength": 6,
            "speed": 9,
            "stamina": 5,
            "fight_rating": "Medium-Hard"
        },
        "best_bait": ["live_bait", "spoon_lure", "cigar_minnow"],
        "best_time": ["morning", "afternoon"],
        "season": ["spring", "summer", "fall"],
        "cooking_grade": "B+",
        "flavor_profile": "Rich, oily, smoky",
        "icon": "🐟",
        "color": "#708090"
    },
    
    # DEEP SEA (Stage 4) - 5 fish
    "giant_squid_deep": {
        "id": "giant_squid_deep",
        "name": "Giant Squid",
        "scientific_name": "Architeuthis dux",
        "biotope": "saltwater",
        "stage": "deep_sea",
        "rarity": "epic",
        "size_range": {"min": 300, "max": 1300, "unit": "cm"},
        "weight_range": {"min": 150, "max": 500, "unit": "kg"},
        "base_value": 1500,
        "xp_reward": 300,
        "description": "A mythical creature from the abyss.",
        "stats": {
            "strength": 10,
            "speed": 6,
            "stamina": 9,
            "fight_rating": "Legendary"
        },
        "best_bait": ["deep_glow_lure", "large_squid"],
        "best_time": ["night"],
        "season": ["all"],
        "cooking_grade": "B",
        "flavor_profile": "Chewy, unique",
        "icon": "🦑",
        "color": "#8B008B"
    },
    "oarfish_deep": {
        "id": "oarfish_deep",
        "name": "Giant Oarfish",
        "scientific_name": "Regalecus glesne",
        "biotope": "saltwater",
        "stage": "deep_sea",
        "rarity": "epic",
        "size_range": {"min": 300, "max": 1100, "unit": "cm"},
        "weight_range": {"min": 100, "max": 270, "unit": "kg"},
        "base_value": 1200,
        "xp_reward": 280,
        "description": "The legendary sea serpent - world's longest bony fish.",
        "stats": {
            "strength": 6,
            "speed": 4,
            "stamina": 8,
            "fight_rating": "Hard"
        },
        "best_bait": ["deep_bait", "krill_swarm"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "C",
        "flavor_profile": "Gelatinous, rare delicacy",
        "icon": "🐉",
        "color": "#C0C0C0"
    },
    "coelacanth": {
        "id": "coelacanth",
        "name": "Coelacanth",
        "scientific_name": "Latimeria chalumnae",
        "biotope": "saltwater",
        "stage": "deep_sea",
        "rarity": "legendary",
        "size_range": {"min": 120, "max": 200, "unit": "cm"},
        "weight_range": {"min": 50, "max": 100, "unit": "kg"},
        "base_value": 3000,
        "xp_reward": 500,
        "description": "A living fossil unchanged for 400 million years.",
        "stats": {
            "strength": 5,
            "speed": 3,
            "stamina": 7,
            "fight_rating": "Medium"
        },
        "best_bait": ["ancient_bait", "deep_fish"],
        "best_time": ["night"],
        "season": ["all"],
        "cooking_grade": "N/A",
        "flavor_profile": "Protected species - catch & release",
        "icon": "🦴",
        "color": "#483D8B"
    },
    "anglerfish": {
        "id": "anglerfish",
        "name": "Deep Sea Anglerfish",
        "scientific_name": "Melanocetus johnsonii",
        "biotope": "saltwater",
        "stage": "deep_sea",
        "rarity": "rare",
        "size_range": {"min": 10, "max": 45, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 5, "unit": "kg"},
        "base_value": 400,
        "xp_reward": 100,
        "description": "A bizarre fish with bioluminescent lure.",
        "stats": {
            "strength": 3,
            "speed": 2,
            "stamina": 6,
            "fight_rating": "Easy"
        },
        "best_bait": ["glow_bait", "small_fish"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "B",
        "flavor_profile": "Firm, mild, unique",
        "icon": "🎣",
        "color": "#2F4F4F"
    },
    "gulper_eel": {
        "id": "gulper_eel",
        "name": "Gulper Eel",
        "scientific_name": "Eurypharynx pelecanoides",
        "biotope": "saltwater",
        "stage": "deep_sea",
        "rarity": "rare",
        "size_range": {"min": 60, "max": 100, "unit": "cm"},
        "weight_range": {"min": 0.5, "max": 2, "unit": "kg"},
        "base_value": 350,
        "xp_reward": 85,
        "description": "A strange eel with enormous expandable mouth.",
        "stats": {
            "strength": 2,
            "speed": 3,
            "stamina": 5,
            "fight_rating": "Easy"
        },
        "best_bait": ["deep_bait", "small_fish"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "C",
        "flavor_profile": "Exotic, acquired taste",
        "icon": "🐍",
        "color": "#000000"
    },
    
    # ARCTIC OCEAN (Stage 5) - 5 fish
    "arctic_cod": {
        "id": "arctic_cod",
        "name": "Arctic Cod",
        "scientific_name": "Boreogadus saida",
        "biotope": "saltwater",
        "stage": "arctic_ocean",
        "rarity": "common",
        "size_range": {"min": 15, "max": 35, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 0.5, "unit": "kg"},
        "base_value": 100,
        "xp_reward": 30,
        "description": "The most abundant fish in Arctic waters.",
        "stats": {
            "strength": 2,
            "speed": 4,
            "stamina": 5,
            "fight_rating": "Easy"
        },
        "best_bait": ["ice_worm", "small_shrimp"],
        "best_time": ["any"],
        "season": ["winter"],
        "cooking_grade": "A",
        "flavor_profile": "Mild, flaky, delicate",
        "icon": "🐟",
        "color": "#87CEEB"
    },
    "greenland_shark": {
        "id": "greenland_shark",
        "name": "Greenland Shark",
        "scientific_name": "Somniosus microcephalus",
        "biotope": "saltwater",
        "stage": "arctic_ocean",
        "rarity": "epic",
        "size_range": {"min": 300, "max": 700, "unit": "cm"},
        "weight_range": {"min": 400, "max": 1400, "unit": "kg"},
        "base_value": 2000,
        "xp_reward": 400,
        "description": "One of the longest-lived vertebrates - up to 500 years.",
        "stats": {
            "strength": 10,
            "speed": 2,
            "stamina": 10,
            "fight_rating": "Legendary"
        },
        "best_bait": ["seal_blubber", "large_fish"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "C",
        "flavor_profile": "Toxic when fresh, fermented delicacy",
        "icon": "🦈",
        "color": "#2F4F4F"
    },
    "arctic_char_sea": {
        "id": "arctic_char_sea",
        "name": "Sea-Run Arctic Char",
        "scientific_name": "Salvelinus alpinus",
        "biotope": "saltwater",
        "stage": "arctic_ocean",
        "rarity": "uncommon",
        "size_range": {"min": 40, "max": 75, "unit": "cm"},
        "weight_range": {"min": 1, "max": 12, "unit": "kg"},
        "base_value": 200,
        "xp_reward": 60,
        "description": "The northernmost freshwater fish, also found at sea.",
        "stats": {
            "strength": 5,
            "speed": 6,
            "stamina": 6,
            "fight_rating": "Medium"
        },
        "best_bait": ["ice_fly", "shrimp", "spoon_lure"],
        "best_time": ["morning", "evening"],
        "season": ["summer"],
        "cooking_grade": "A+",
        "flavor_profile": "Rich, pink, salmon-like",
        "icon": "🐟",
        "color": "#FF6B6B"
    },
    "polar_sculpin": {
        "id": "polar_sculpin",
        "name": "Polar Sculpin",
        "scientific_name": "Cottunculus microps",
        "biotope": "saltwater",
        "stage": "arctic_ocean",
        "rarity": "uncommon",
        "size_range": {"min": 15, "max": 30, "unit": "cm"},
        "weight_range": {"min": 0.1, "max": 1, "unit": "kg"},
        "base_value": 120,
        "xp_reward": 35,
        "description": "A bottom-dwelling fish with antifreeze in its blood.",
        "stats": {
            "strength": 2,
            "speed": 2,
            "stamina": 6,
            "fight_rating": "Easy"
        },
        "best_bait": ["ice_worm", "shrimp"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "B",
        "flavor_profile": "Mild, firm",
        "icon": "🐟",
        "color": "#D3D3D3"
    },
    "ice_fish": {
        "id": "ice_fish",
        "name": "Antarctic Icefish",
        "scientific_name": "Channichthyidae",
        "biotope": "saltwater",
        "stage": "arctic_ocean",
        "rarity": "rare",
        "size_range": {"min": 25, "max": 75, "unit": "cm"},
        "weight_range": {"min": 0.3, "max": 3, "unit": "kg"},
        "base_value": 300,
        "xp_reward": 80,
        "description": "The only vertebrate with no red blood cells - transparent blood.",
        "stats": {
            "strength": 2,
            "speed": 4,
            "stamina": 5,
            "fight_rating": "Easy"
        },
        "best_bait": ["krill", "small_fish"],
        "best_time": ["any"],
        "season": ["all"],
        "cooking_grade": "A",
        "flavor_profile": "Delicate, sweet, rare",
        "icon": "❄️",
        "color": "#E0FFFF"
    }
}
