// ========================================================================
// EXPANDED RECIPE BOOK - 50+ Recipes for Enhanced Cooking System
// Complete recipe database with unlock conditions and special effects
// ========================================================================

// ==================== RECIPE CATEGORIES ====================
export const RECIPE_CATEGORIES = {
  APPETIZER: { id: 'appetizer', name: 'Appetizers', icon: '🥗', color: 'from-green-500 to-emerald-600' },
  SOUP: { id: 'soup', name: 'Soups', icon: '🥣', color: 'from-amber-500 to-orange-600' },
  MAIN: { id: 'main', name: 'Main Courses', icon: '🍽️', color: 'from-red-500 to-rose-600' },
  SUSHI: { id: 'sushi', name: 'Sushi & Sashimi', icon: '🍣', color: 'from-pink-500 to-rose-600' },
  FRIED: { id: 'fried', name: 'Fried Dishes', icon: '🍳', color: 'from-yellow-500 to-amber-600' },
  GRILLED: { id: 'grilled', name: 'Grilled', icon: '🔥', color: 'from-orange-500 to-red-600' },
  STEW: { id: 'stew', name: 'Stews & Curries', icon: '🍲', color: 'from-brown-500 to-amber-700' },
  PASTA: { id: 'pasta', name: 'Pasta & Noodles', icon: '🍝', color: 'from-yellow-400 to-orange-500' },
  DESSERT: { id: 'dessert', name: 'Desserts', icon: '🍰', color: 'from-pink-400 to-purple-500' },
  LEGENDARY: { id: 'legendary', name: 'Legendary', icon: '👑', color: 'from-yellow-400 to-orange-500' },
};

// ==================== COMPLETE RECIPE DATABASE ====================
export const EXPANDED_RECIPES = {
  // ========== APPETIZERS (Tier 1) ==========
  fish_crackers: {
    id: 'fish_crackers',
    name: 'Fish Crackers',
    category: 'appetizer',
    tier: 1,
    rarity: 'common',
    icon: '🍘',
    description: 'Crispy fish-shaped snacks',
    ingredients: [
      { id: 'minnow_fillet', amount: 1 },
      { id: 'breadcrumbs', amount: 1 },
    ],
    cookingTime: 5,
    difficulty: 'easy',
    reward: { points: 30, xp: 5 },
    unlockLevel: 1,
    miniGame: 'timing',
  },
  seaweed_salad: {
    id: 'seaweed_salad',
    name: 'Seaweed Salad',
    category: 'appetizer',
    tier: 1,
    rarity: 'common',
    icon: '🥗',
    description: 'Fresh ocean greens',
    ingredients: [
      { id: 'seaweed', amount: 3 },
      { id: 'sea_salt', amount: 1 },
      { id: 'lemon', amount: 1 },
    ],
    cookingTime: 3,
    difficulty: 'easy',
    reward: { points: 40, xp: 8 },
    unlockLevel: 1,
    miniGame: 'timing',
  },
  fish_cakes: {
    id: 'fish_cakes',
    name: 'Mini Fish Cakes',
    category: 'appetizer',
    tier: 1,
    rarity: 'common',
    icon: '🥮',
    description: 'Bite-sized fish patties',
    ingredients: [
      { id: 'minnow_fillet', amount: 2 },
      { id: 'breadcrumbs', amount: 2 },
      { id: 'garlic', amount: 1 },
    ],
    cookingTime: 8,
    difficulty: 'easy',
    reward: { points: 60, xp: 12 },
    unlockLevel: 2,
    miniGame: 'flipping',
  },
  
  // ========== SOUPS (Tier 1-2) ==========
  simple_fish_soup: {
    id: 'simple_fish_soup',
    name: 'Simple Fish Soup',
    category: 'soup',
    tier: 1,
    rarity: 'common',
    icon: '🥣',
    description: 'Warm and comforting',
    ingredients: [
      { id: 'minnow_fillet', amount: 1 },
      { id: 'seaweed', amount: 2 },
      { id: 'sea_salt', amount: 1 },
    ],
    cookingTime: 8,
    difficulty: 'easy',
    reward: { points: 75, xp: 15 },
    unlockLevel: 1,
    miniGame: 'stirring',
  },
  miso_fish_soup: {
    id: 'miso_fish_soup',
    name: 'Miso Fish Soup',
    category: 'soup',
    tier: 2,
    rarity: 'uncommon',
    icon: '🍜',
    description: 'Traditional Japanese soup',
    ingredients: [
      { id: 'perch_fillet', amount: 1 },
      { id: 'kelp', amount: 2 },
      { id: 'garlic', amount: 1 },
      { id: 'soy_sauce', amount: 1 },
    ],
    cookingTime: 12,
    difficulty: 'medium',
    reward: { points: 150, xp: 30 },
    unlockLevel: 4,
    miniGame: 'stirring',
  },
  chowder: {
    id: 'chowder',
    name: 'Creamy Fish Chowder',
    category: 'soup',
    tier: 2,
    rarity: 'uncommon',
    icon: '🥣',
    description: 'Rich and creamy',
    ingredients: [
      { id: 'bass_fillet', amount: 1 },
      { id: 'butter', amount: 2 },
      { id: 'garlic', amount: 1 },
      { id: 'herbs', amount: 1 },
    ],
    cookingTime: 15,
    difficulty: 'medium',
    reward: { points: 200, xp: 40 },
    unlockLevel: 6,
    miniGame: 'stirring',
  },
  bouillabaisse: {
    id: 'bouillabaisse',
    name: 'Bouillabaisse',
    category: 'soup',
    tier: 3,
    rarity: 'rare',
    icon: '🍲',
    description: 'French seafood stew',
    ingredients: [
      { id: 'bass_fillet', amount: 1 },
      { id: 'pike_fillet', amount: 1 },
      { id: 'garlic', amount: 2 },
      { id: 'herbs', amount: 2 },
      { id: 'truffle_oil', amount: 1 },
    ],
    cookingTime: 25,
    difficulty: 'hard',
    reward: { points: 450, xp: 90 },
    unlockLevel: 12,
    miniGame: 'precision',
  },
  
  // ========== GRILLED DISHES (Tier 1-3) ==========
  grilled_minnow: {
    id: 'grilled_minnow',
    name: 'Grilled Minnow',
    category: 'grilled',
    tier: 1,
    rarity: 'common',
    icon: '🐟',
    description: 'Simple but tasty',
    ingredients: [
      { id: 'minnow_fillet', amount: 2 },
      { id: 'sea_salt', amount: 1 },
    ],
    cookingTime: 5,
    difficulty: 'easy',
    reward: { points: 50, xp: 10 },
    unlockLevel: 1,
    miniGame: 'timing',
  },
  grilled_perch: {
    id: 'grilled_perch',
    name: 'Herb Grilled Perch',
    category: 'grilled',
    tier: 1,
    rarity: 'common',
    icon: '🐠',
    description: 'Fragrant and delicious',
    ingredients: [
      { id: 'perch_fillet', amount: 1 },
      { id: 'herbs', amount: 1 },
      { id: 'lemon', amount: 1 },
    ],
    cookingTime: 8,
    difficulty: 'easy',
    reward: { points: 80, xp: 16 },
    unlockLevel: 2,
    miniGame: 'timing',
  },
  lemon_bass: {
    id: 'lemon_bass',
    name: 'Lemon Butter Bass',
    category: 'grilled',
    tier: 2,
    rarity: 'uncommon',
    icon: '🍋',
    description: 'Elegant citrus dish',
    ingredients: [
      { id: 'bass_fillet', amount: 1 },
      { id: 'lemon', amount: 2 },
      { id: 'butter', amount: 2 },
      { id: 'herbs', amount: 1 },
    ],
    cookingTime: 15,
    difficulty: 'medium',
    reward: { points: 200, xp: 40 },
    unlockLevel: 5,
    miniGame: 'seasoning',
  },
  teriyaki_salmon: {
    id: 'teriyaki_salmon',
    name: 'Teriyaki Salmon',
    category: 'grilled',
    tier: 2,
    rarity: 'uncommon',
    icon: '🍣',
    description: 'Sweet and savory glaze',
    ingredients: [
      { id: 'salmon_fillet', amount: 1 },
      { id: 'soy_sauce', amount: 2 },
      { id: 'garlic', amount: 1 },
      { id: 'rice', amount: 1 },
    ],
    cookingTime: 18,
    difficulty: 'medium',
    reward: { points: 250, xp: 50 },
    unlockLevel: 7,
    miniGame: 'timing',
  },
  grilled_swordfish: {
    id: 'grilled_swordfish',
    name: 'Grilled Swordfish Steak',
    category: 'grilled',
    tier: 3,
    rarity: 'rare',
    icon: '⚔️',
    description: 'Premium seafood steak',
    ingredients: [
      { id: 'swordfish_steak', amount: 1 },
      { id: 'truffle_oil', amount: 1 },
      { id: 'herbs', amount: 2 },
      { id: 'lemon', amount: 1 },
    ],
    cookingTime: 20,
    difficulty: 'hard',
    reward: { points: 500, xp: 100 },
    unlockLevel: 14,
    miniGame: 'precision',
  },
  
  // ========== FRIED DISHES (Tier 1-3) ==========
  fried_minnow: {
    id: 'fried_minnow',
    name: 'Crispy Fried Minnow',
    category: 'fried',
    tier: 1,
    rarity: 'common',
    icon: '🍳',
    description: 'Golden and crunchy',
    ingredients: [
      { id: 'minnow_fillet', amount: 2 },
      { id: 'breadcrumbs', amount: 2 },
      { id: 'sea_salt', amount: 1 },
    ],
    cookingTime: 6,
    difficulty: 'easy',
    reward: { points: 55, xp: 11 },
    unlockLevel: 1,
    miniGame: 'flipping',
  },
  fish_and_chips: {
    id: 'fish_and_chips',
    name: 'Fish and Chips',
    category: 'fried',
    tier: 2,
    rarity: 'uncommon',
    icon: '🍟',
    description: 'British classic',
    ingredients: [
      { id: 'cod_fillet', amount: 1 },
      { id: 'breadcrumbs', amount: 3 },
      { id: 'lemon', amount: 1 },
      { id: 'sea_salt', amount: 1 },
    ],
    cookingTime: 15,
    difficulty: 'medium',
    reward: { points: 175, xp: 35 },
    unlockLevel: 5,
    miniGame: 'flipping',
  },
  tempura: {
    id: 'tempura',
    name: 'Seafood Tempura',
    category: 'fried',
    tier: 2,
    rarity: 'uncommon',
    icon: '🍤',
    description: 'Light and crispy Japanese',
    ingredients: [
      { id: 'perch_fillet', amount: 1 },
      { id: 'seaweed', amount: 1 },
      { id: 'breadcrumbs', amount: 2 },
      { id: 'soy_sauce', amount: 1 },
    ],
    cookingTime: 12,
    difficulty: 'medium',
    reward: { points: 180, xp: 36 },
    unlockLevel: 6,
    miniGame: 'flipping',
  },
  southern_catfish: {
    id: 'southern_catfish',
    name: 'Southern Fried Catfish',
    category: 'fried',
    tier: 2,
    rarity: 'uncommon',
    icon: '🐡',
    description: 'Crispy cornmeal coating',
    ingredients: [
      { id: 'catfish_fillet', amount: 1 },
      { id: 'breadcrumbs', amount: 2 },
      { id: 'garlic', amount: 1 },
      { id: 'herbs', amount: 1 },
    ],
    cookingTime: 14,
    difficulty: 'medium',
    reward: { points: 220, xp: 44 },
    unlockLevel: 7,
    miniGame: 'flipping',
  },
  
  // ========== SUSHI & SASHIMI (Tier 2-4) ==========
  basic_maki: {
    id: 'basic_maki',
    name: 'Basic Maki Roll',
    category: 'sushi',
    tier: 2,
    rarity: 'uncommon',
    icon: '🍣',
    description: 'Simple sushi roll',
    ingredients: [
      { id: 'perch_fillet', amount: 1 },
      { id: 'rice', amount: 2 },
      { id: 'nori', amount: 1 },
    ],
    cookingTime: 12,
    difficulty: 'medium',
    reward: { points: 150, xp: 30 },
    unlockLevel: 5,
    miniGame: 'rolling',
  },
  salmon_sashimi: {
    id: 'salmon_sashimi',
    name: 'Salmon Sashimi',
    category: 'sushi',
    tier: 2,
    rarity: 'uncommon',
    icon: '🍣',
    description: 'Fresh sliced salmon',
    ingredients: [
      { id: 'salmon_fillet', amount: 1 },
      { id: 'wasabi', amount: 1 },
      { id: 'soy_sauce', amount: 1 },
    ],
    cookingTime: 8,
    difficulty: 'medium',
    reward: { points: 200, xp: 40 },
    unlockLevel: 6,
    miniGame: 'slicing',
  },
  dragon_roll: {
    id: 'dragon_roll',
    name: 'Dragon Roll',
    category: 'sushi',
    tier: 3,
    rarity: 'rare',
    icon: '🐉',
    description: 'Elaborate special roll',
    ingredients: [
      { id: 'eel_meat', amount: 1 },
      { id: 'rice', amount: 2 },
      { id: 'nori', amount: 1 },
      { id: 'wasabi', amount: 1 },
      { id: 'soy_sauce', amount: 1 },
    ],
    cookingTime: 20,
    difficulty: 'hard',
    reward: { points: 400, xp: 80 },
    unlockLevel: 10,
    miniGame: 'rolling',
  },
  tuna_tataki: {
    id: 'tuna_tataki',
    name: 'Tuna Tataki',
    category: 'sushi',
    tier: 3,
    rarity: 'rare',
    icon: '🥩',
    description: 'Seared tuna perfection',
    ingredients: [
      { id: 'tuna_steak', amount: 1 },
      { id: 'soy_sauce', amount: 2 },
      { id: 'garlic', amount: 1 },
      { id: 'lemon', amount: 1 },
    ],
    cookingTime: 15,
    difficulty: 'hard',
    reward: { points: 450, xp: 90 },
    unlockLevel: 12,
    miniGame: 'precision',
  },
  omakase_platter: {
    id: 'omakase_platter',
    name: 'Omakase Platter',
    category: 'sushi',
    tier: 4,
    rarity: 'epic',
    icon: '🍱',
    description: "Chef's choice selection",
    ingredients: [
      { id: 'salmon_fillet', amount: 1 },
      { id: 'tuna_steak', amount: 1 },
      { id: 'eel_meat', amount: 1 },
      { id: 'rice', amount: 3 },
      { id: 'nori', amount: 2 },
      { id: 'wasabi', amount: 2 },
    ],
    cookingTime: 35,
    difficulty: 'expert',
    reward: { points: 1000, xp: 200 },
    unlockLevel: 18,
    miniGame: 'masterChef',
    specialEffect: { buff: 'sushi_master', duration: 600 },
  },
  
  // ========== STEWS & CURRIES (Tier 2-4) ==========
  catfish_gumbo: {
    id: 'catfish_gumbo',
    name: 'Catfish Gumbo',
    category: 'stew',
    tier: 2,
    rarity: 'uncommon',
    icon: '🍲',
    description: 'Rich Southern stew',
    ingredients: [
      { id: 'catfish_fillet', amount: 2 },
      { id: 'kelp', amount: 2 },
      { id: 'garlic', amount: 2 },
      { id: 'herbs', amount: 1 },
    ],
    cookingTime: 25,
    difficulty: 'medium',
    reward: { points: 300, xp: 60 },
    unlockLevel: 7,
    miniGame: 'stirring',
  },
  thai_fish_curry: {
    id: 'thai_fish_curry',
    name: 'Thai Fish Curry',
    category: 'stew',
    tier: 3,
    rarity: 'rare',
    icon: '🍛',
    description: 'Spicy coconut curry',
    ingredients: [
      { id: 'bass_fillet', amount: 2 },
      { id: 'garlic', amount: 2 },
      { id: 'herbs', amount: 2 },
      { id: 'dragon_spice', amount: 1 },
    ],
    cookingTime: 30,
    difficulty: 'hard',
    reward: { points: 550, xp: 110 },
    unlockLevel: 13,
    miniGame: 'stirring',
    specialEffect: { buff: 'spicy_boost', duration: 300 },
  },
  cioppino: {
    id: 'cioppino',
    name: 'Cioppino',
    category: 'stew',
    tier: 3,
    rarity: 'rare',
    icon: '🍲',
    description: 'Italian seafood stew',
    ingredients: [
      { id: 'bass_fillet', amount: 1 },
      { id: 'catfish_fillet', amount: 1 },
      { id: 'garlic', amount: 2 },
      { id: 'herbs', amount: 2 },
      { id: 'lemon', amount: 1 },
    ],
    cookingTime: 35,
    difficulty: 'hard',
    reward: { points: 500, xp: 100 },
    unlockLevel: 11,
    miniGame: 'stirring',
  },
  
  // ========== PASTA & NOODLES (Tier 2-4) ==========
  fish_pasta: {
    id: 'fish_pasta',
    name: 'Fish Pasta',
    category: 'pasta',
    tier: 2,
    rarity: 'uncommon',
    icon: '🍝',
    description: 'Creamy fish sauce pasta',
    ingredients: [
      { id: 'bass_fillet', amount: 1 },
      { id: 'pasta', amount: 2 },
      { id: 'butter', amount: 2 },
      { id: 'garlic', amount: 1 },
    ],
    cookingTime: 18,
    difficulty: 'medium',
    reward: { points: 225, xp: 45 },
    unlockLevel: 6,
    miniGame: 'stirring',
  },
  seafood_linguine: {
    id: 'seafood_linguine',
    name: 'Seafood Linguine',
    category: 'pasta',
    tier: 3,
    rarity: 'rare',
    icon: '🍝',
    description: 'Italian seafood classic',
    ingredients: [
      { id: 'bass_fillet', amount: 1 },
      { id: 'catfish_fillet', amount: 1 },
      { id: 'pasta', amount: 2 },
      { id: 'garlic', amount: 2 },
      { id: 'herbs', amount: 1 },
      { id: 'truffle_oil', amount: 1 },
    ],
    cookingTime: 25,
    difficulty: 'hard',
    reward: { points: 450, xp: 90 },
    unlockLevel: 10,
    miniGame: 'stirring',
  },
  
  // ========== MAIN COURSES (Tier 3-4) ==========
  pike_en_croute: {
    id: 'pike_en_croute',
    name: 'Pike en Croûte',
    category: 'main',
    tier: 3,
    rarity: 'rare',
    icon: '🥧',
    description: 'French pastry-wrapped pike',
    ingredients: [
      { id: 'pike_fillet', amount: 1 },
      { id: 'butter', amount: 3 },
      { id: 'herbs', amount: 2 },
      { id: 'breadcrumbs', amount: 2 },
    ],
    cookingTime: 30,
    difficulty: 'hard',
    reward: { points: 500, xp: 100 },
    unlockLevel: 10,
    miniGame: 'precision',
  },
  seafood_paella: {
    id: 'seafood_paella',
    name: 'Seafood Paella',
    category: 'main',
    tier: 3,
    rarity: 'rare',
    icon: '🥘',
    description: 'Spanish rice masterpiece',
    ingredients: [
      { id: 'bass_fillet', amount: 1 },
      { id: 'catfish_fillet', amount: 1 },
      { id: 'rice', amount: 3 },
      { id: 'garlic', amount: 2 },
      { id: 'herbs', amount: 2 },
    ],
    cookingTime: 35,
    difficulty: 'hard',
    reward: { points: 600, xp: 120 },
    unlockLevel: 12,
    miniGame: 'timing',
  },
  truffle_pike: {
    id: 'truffle_pike',
    name: 'Truffle-Crusted Pike',
    category: 'main',
    tier: 3,
    rarity: 'rare',
    icon: '🍄',
    description: 'Luxurious truffle experience',
    ingredients: [
      { id: 'pike_fillet', amount: 1 },
      { id: 'truffle_oil', amount: 1 },
      { id: 'butter', amount: 2 },
      { id: 'sea_salt', amount: 1 },
    ],
    cookingTime: 25,
    difficulty: 'hard',
    reward: { points: 750, xp: 150 },
    unlockLevel: 15,
    miniGame: 'seasoning',
  },
  
  // ========== EXPERT RECIPES (Tier 4) ==========
  dragons_feast: {
    id: 'dragons_feast',
    name: "Dragon's Feast",
    category: 'main',
    tier: 4,
    rarity: 'epic',
    icon: '🐉',
    description: 'Legendary spicy dish',
    ingredients: [
      { id: 'pike_fillet', amount: 2 },
      { id: 'dragon_spice', amount: 1 },
      { id: 'truffle_oil', amount: 1 },
      { id: 'herbs', amount: 3 },
    ],
    cookingTime: 45,
    difficulty: 'expert',
    reward: { points: 1500, xp: 300 },
    unlockLevel: 20,
    miniGame: 'precision',
    specialEffect: { buff: 'fire_resistance', duration: 300 },
  },
  pearl_consomme: {
    id: 'pearl_consomme',
    name: 'Pearl Consommé',
    category: 'soup',
    tier: 4,
    rarity: 'epic',
    icon: '⚪',
    description: 'Crystal clear perfection',
    ingredients: [
      { id: 'bass_fillet', amount: 2 },
      { id: 'pearl', amount: 1 },
      { id: 'kelp', amount: 3 },
      { id: 'herbs', amount: 2 },
    ],
    cookingTime: 50,
    difficulty: 'expert',
    reward: { points: 1200, xp: 250 },
    unlockLevel: 18,
    miniGame: 'stirring',
    specialEffect: { buff: 'clarity', duration: 600 },
  },
  mermaids_blessing: {
    id: 'mermaids_blessing',
    name: "Mermaid's Blessing",
    category: 'main',
    tier: 4,
    rarity: 'epic',
    icon: '🧜‍♀️',
    description: 'Enchanted seafood delicacy',
    ingredients: [
      { id: 'pike_fillet', amount: 1 },
      { id: 'mermaid_tear', amount: 1 },
      { id: 'sea_lettuce', amount: 2 },
      { id: 'lemon', amount: 2 },
    ],
    cookingTime: 40,
    difficulty: 'expert',
    reward: { points: 2000, xp: 400 },
    unlockLevel: 22,
    miniGame: 'precision',
    specialEffect: { buff: 'luck_boost', duration: 900 },
  },
  anglerfish_lantern: {
    id: 'anglerfish_lantern',
    name: 'Anglerfish Lantern',
    category: 'main',
    tier: 4,
    rarity: 'epic',
    icon: '🔦',
    description: 'Glowing deep sea dish',
    ingredients: [
      { id: 'angler_meat', amount: 1 },
      { id: 'bioluminescent_orb', amount: 1 },
      { id: 'deep_sea_salt', amount: 1 },
      { id: 'truffle_oil', amount: 1 },
    ],
    cookingTime: 55,
    difficulty: 'expert',
    reward: { points: 1800, xp: 360 },
    unlockLevel: 24,
    miniGame: 'precision',
    specialEffect: { buff: 'night_vision', duration: 1200 },
  },
  
  // ========== LEGENDARY RECIPES (Tier 5) ==========
  golden_feast: {
    id: 'golden_feast',
    name: 'Golden Feast',
    category: 'legendary',
    tier: 5,
    rarity: 'legendary',
    icon: '👑',
    description: 'The ultimate culinary achievement',
    ingredients: [
      { id: 'golden_koi_fillet', amount: 1 },
      { id: 'golden_scale', amount: 1 },
      { id: 'truffle_oil', amount: 2 },
      { id: 'dragon_spice', amount: 1 },
      { id: 'mermaid_tear', amount: 1 },
    ],
    cookingTime: 120,
    difficulty: 'legendary',
    reward: { points: 10000, xp: 2000 },
    unlockLevel: 30,
    miniGame: 'masterChef',
    specialEffect: { buff: 'golden_aura', duration: 1800 },
  },
  poseidons_platter: {
    id: 'poseidons_platter',
    name: "Poseidon's Platter",
    category: 'legendary',
    tier: 5,
    rarity: 'legendary',
    icon: '🔱',
    description: 'Fit for a sea god',
    ingredients: [
      { id: 'golden_koi_fillet', amount: 1 },
      { id: 'pike_fillet', amount: 2 },
      { id: 'pearl', amount: 2 },
      { id: 'ocean_mushroom', amount: 2 },
      { id: 'truffle_oil', amount: 1 },
    ],
    cookingTime: 90,
    difficulty: 'legendary',
    reward: { points: 8000, xp: 1600 },
    unlockLevel: 28,
    miniGame: 'masterChef',
    specialEffect: { buff: 'ocean_mastery', duration: 1200 },
  },
  leviathan_steak: {
    id: 'leviathan_steak',
    name: 'Leviathan Steak',
    category: 'legendary',
    tier: 5,
    rarity: 'legendary',
    icon: '🐋',
    description: 'Mythical sea beast meat',
    ingredients: [
      { id: 'swordfish_steak', amount: 2 },
      { id: 'tuna_steak', amount: 2 },
      { id: 'dragon_spice', amount: 2 },
      { id: 'truffle_oil', amount: 2 },
      { id: 'pearl', amount: 1 },
    ],
    cookingTime: 100,
    difficulty: 'legendary',
    reward: { points: 7500, xp: 1500 },
    unlockLevel: 26,
    miniGame: 'masterChef',
    specialEffect: { buff: 'strength_boost', duration: 1500 },
  },
  
  // ========== SECRET RECIPES (Special unlocks) ==========
  midnight_catch: {
    id: 'midnight_catch',
    name: 'Midnight Catch',
    category: 'legendary',
    tier: 5,
    rarity: 'legendary',
    icon: '🌙',
    description: 'Made only at midnight',
    ingredients: [
      { id: 'eel_meat', amount: 2 },
      { id: 'moonstone_powder', amount: 1 },
      { id: 'ocean_mushroom', amount: 2 },
      { id: 'herbs', amount: 3 },
    ],
    cookingTime: 60,
    difficulty: 'legendary',
    reward: { points: 5000, xp: 1000 },
    unlockLevel: 25,
    miniGame: 'precision',
    specialEffect: { buff: 'midnight_mastery', duration: 2400 },
    unlockCondition: 'Cook during midnight hour',
  },
  storm_survivor: {
    id: 'storm_survivor',
    name: 'Storm Survivor',
    category: 'legendary',
    tier: 5,
    rarity: 'legendary',
    icon: '⛈️',
    description: 'Fish caught in storms',
    ingredients: [
      { id: 'pike_fillet', amount: 2 },
      { id: 'lightning_essence', amount: 1 },
      { id: 'deep_sea_salt', amount: 2 },
      { id: 'dragon_spice', amount: 1 },
    ],
    cookingTime: 75,
    difficulty: 'legendary',
    reward: { points: 6000, xp: 1200 },
    unlockLevel: 27,
    miniGame: 'precision',
    specialEffect: { buff: 'storm_power', duration: 1800 },
    unlockCondition: 'Catch 10 fish during storms',
  },
};

// ==================== RECIPE UTILITY FUNCTIONS ====================
export const getRecipesByCategory = (category) => {
  return Object.values(EXPANDED_RECIPES).filter(r => r.category === category);
};

export const getRecipesByTier = (tier) => {
  return Object.values(EXPANDED_RECIPES).filter(r => r.tier === tier);
};

export const getRecipesByRarity = (rarity) => {
  return Object.values(EXPANDED_RECIPES).filter(r => r.rarity === rarity);
};

export const getAvailableRecipes = (chefLevel) => {
  return Object.values(EXPANDED_RECIPES).filter(r => chefLevel >= r.unlockLevel);
};

export const getRecipeStats = () => {
  const recipes = Object.values(EXPANDED_RECIPES);
  return {
    total: recipes.length,
    byTier: {
      1: recipes.filter(r => r.tier === 1).length,
      2: recipes.filter(r => r.tier === 2).length,
      3: recipes.filter(r => r.tier === 3).length,
      4: recipes.filter(r => r.tier === 4).length,
      5: recipes.filter(r => r.tier === 5).length,
    },
    byRarity: {
      common: recipes.filter(r => r.rarity === 'common').length,
      uncommon: recipes.filter(r => r.rarity === 'uncommon').length,
      rare: recipes.filter(r => r.rarity === 'rare').length,
      epic: recipes.filter(r => r.rarity === 'epic').length,
      legendary: recipes.filter(r => r.rarity === 'legendary').length,
    },
    byCategory: Object.keys(RECIPE_CATEGORIES).reduce((acc, cat) => {
      acc[cat.toLowerCase()] = recipes.filter(r => r.category === cat.toLowerCase()).length;
      return acc;
    }, {}),
  };
};

export default EXPANDED_RECIPES;
